### ISSUE TITLE
Bug: clearing samples on the microscopy prep page in the microscopy experimental technique

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#108]
When you click "Clear All" after adding samples on the microscopy prep page of the microscopy experimental technique, the checkboxes become unchecked (as appropriate), but the information in the conditions column remains (instead of disappearing). The information in the conditions column is in black text and the unselected radio button is still apparent. This is true in both SUTD Exercise 1 and 2.

https://starcellbio.mit.edu/#view=microscopy&experiment_id=scb_Experiment_dj3ol41nnh7ag&assignment_id=sutd_intro_biology&microscopy_id=scb_Microscopy_1bcdf2229bkfqn

**Comment by annagav** [comment]
Looks like this is fixed.
