### ISSUE TITLE
Blind indexing on group for logged in user

### ISSUE THREAD

**Issue by bdero** [starteam/starcellbio_html#110]
If the user is logged in, the call to `/scb/get_user.js` errors if the account doesn't have a group due to blindly indexing for the first group, which then causes JS errors, which causes BSOD.

See this line:
https://github.com/starteam/starcellbio_html/blob/18370f3811c45590a7938d973aa153458b58e96b/StarCellBio/views.py#L91

This is pretty low priority since this can only really happen when generating an account using a method other than the registration form (e.g. generating a service account).

**Comment by pdpinch** [comment]
@annagav do you think you can fix this?

**Comment by annagav** [comment]
Yes, I can do this.

**Comment by bdero** [comment]
It's worth noting that there's an implicit design decision here, since not having a group is definitely undefined behavior given how the app is written.

**Comment by pdpinch** [comment]
Is not having a group significantly differently from accessing the site without registering?

**Comment by bdero** [comment]
I'm not sure, but hopefully it ends up not being so different. When not signed in, the response is `var get_user_result = {"account_type": "", "name": ""};`.
The worst case scenario would probably be that there's a bunch of JS that determines whether the user is logged in or not by checking is the `account_type` string is empty.
