### ISSUE TITLE
NSF #2: Can't adjust bisector gate after is has been applied

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#111]
(tested in sample exercise 2, using the current develop branch, 18370f3811)

After I have applied a bisector gate, it appears that I can adjust it by clicking and dragging on the small black, square "handle."

However, when I complete my drag and let go of the mouse, the handle jumps off the plot. 

It appears to be a problem with offset or registration.

**Comment by annagav** [comment]
FACS for NSF Exercise 2 and 3 has not been completed yet. The gates might not be working due to change in scale.

**Comment by pdpinch** [comment]
Indeed, this issue appears to be specific to NSF Exercises. I've edited the title & the milestone, but I'll leave it open until they are fixed.

**Comment by annagav** [comment]
This has been fixed when I implemented the pseudo logarithmic scale for NSF exercises.
