### ISSUE TITLE
SUTD Exercise 2: Adjustment to western blotting bands

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#112]
from @laleman 

> Hi Anna. I just went through Exercise #2 again and we need to do a couple of adjustments to band intensities for western blotting for the anti-cyclin B and anti-Scc1 antibody conditions.  I have highlighted what it should look like under a new version of the excel coding file (Ver3) in yellow. For anti-cyclin B antibody condition, the change will make the blot look more realistic. For the anti-Scc1 condition, the change is to correct an error on my part.

**Comment by laleman** [comment]
SUTD instructors just noticed one more error in western blotting. siRNA #3 treatment should yield a band of the same size and intensity for anti-cyclin E antibody conditions as that of Control siRNA. I have changed the coding excel document with this change (now Ver4) and have highlighted in yellow this change. I kept changes previously requested in this report in yellow as well. Thank you!!!!!!

**Comment by pdpinch** [comment]
@annagav can you add this to the commit you've already done?
