### ISSUE TITLE
Do we still need ui_old?

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#120]
It bugs me every time I see the build script touch this directory. Is it actually necessary?

https://github.com/starteam/starcellbio_html/tree/develop/html_app/ui_old

**Comment by bdero** [comment]
Good question, I'm not actually sure. I really like deleting things, though, so I'll take a look.

**Comment by bdero** [comment]
Ah, looking at my phone, I didn't realize that @annagav was assigned to this.

**Comment by annagav** [comment]
I think it is this ui: http://edison.mit.edu/

**Comment by pdpinch** [comment]
I just pinged Alison & Lourdes again about http://edison.mit.edu/ and cc'ed you. 

@bdero if you have a few minutes, can you tell us if edison is using a particular branch of the project (we have been speculating master)

**Comment by bdero** [comment]
Sure, http://edison.mit.edu points to 21dea9e4dbc536bf77a43d855474f79487260fc9 (branch set to `tufts`), and https://edison.mit.edu points to f6f4e6489c6044fd55659911a68ef767cce67f94 (branch set to `develop`). Both are super old and fairly close to each other. 

Judging by how far the "edison" builds are from the current `develop`, I'm guessing somewhere down the line someone was like:
![we'll do it live](http://cdn.meme.am/instances/52311788.jpg)

**Comment by carsongee** [comment]
wait, plain and ssl have different versions?

**Comment by bdero** [comment]
Yes they do. :-1:

**Comment by carsongee** [comment]
:sparkles: beautiful :sparkles:

**Comment by annagav** [comment]
The ui_old folder is used only in this init function https://github.com/starteam/starcellbio_html/blob/develop/html_app/ui/MainFrame.js#L1000, that according to the comment is not being used anymore.

**Comment by pdpinch** [comment]
What happens if you remove that function?

I see some changes that Shloka made to it, as recently as last June: https://github.com/starteam/starcellbio_html/commit/2cf0734113210d7c486376421ded85702308a628 and https://github.com/starteam/starcellbio_html/commit/d0acee725d611cd55f087aaee64333e1721056dd

**Comment by annagav** [comment]
sections.workarea is not being used anywhere https://github.com/starteam/starcellbio_html/blob/develop/html_app/ui/MainFrame.js#L603
This eliminates the need in WorkspaceView.js.
