### ISSUE TITLE
Is html_app/ui_old still in use ?

### ISSUE THREAD

**Issue by Ferdi** [starteam/starcellbio_html#121]
https://github.com/starteam/starcellbio_html/tree/develop/html_app/ui_old

If not, pls delete them.

**Comment by bdero** [comment]
Well, I do like deleting stuff. I'll take a look.

**Comment by bdero** [comment]
I think this issue is a duplicate of #120

**Comment by Ferdi** [comment]
Sorry, closing this one in favor of #120
