### ISSUE TITLE
Two similar javascript libraries swipe / coinslider

### ISSUE THREAD

**Issue by Ferdi** [starteam/starcellbio_html#122]
They seem to do the same thing (making sliders)

https://github.com/starteam/starcellbio_html/tree/develop/html_app
- Are they both in use ?  
- Can we just use 1 of them
- Only keep the min version of css/js files and delete the rest (http://goo.gl/S5AeDr)

**Comment by annagav** [comment]
I did not find any usages of coinslider in the code.
