### ISSUE TITLE
Decommission edison.mit.edu

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#132]
(This probably isn't the right place to put this issue, but I'm not sure where else to do it -- Trello doesn't seem right either.)

I've gotten confirmation from @ald32 and @laleman that http://edison.mit.edu and https://edison.mit.edu are no longer needed. They were a branch that was used by students at Tufts. At the time, there was no way to register with a course code, so they needed two different servers to support simultaneous courses at MIT and at Tufts. 

We should confirm that the content of the server at :80 and at :443 are both captured somehow, and then we can decommission the server.

**Comment by bdero** [comment]
This is done now.

**Comment by pdpinch** [comment]
Do you think we should do anything with DNS?

**Comment by bdero** [comment]
Good point; I'm actually not 100% sure who to contact about these things. @carsongee should I contact ops-help for mit.edu DNS inquiries?

**Comment by pdpinch** [comment]
Carson didn't see any reason to remove edison from DNS, so I'm closing this.
