### ISSUE TITLE
Can't use Bio52 course code

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#133]
I tried to a create a student account associated with Bio52, but when I log in I get dumped to the home page view and I can't see the Tufts assignments.

**Comment by annagav** [comment]
Tufts assignment was constructed over two years ago and the coding for the assignments belongs to "old assignments" part of master model https://github.com/starteam/starcellbio_html/blob/develop/html_app/master_model.js#L1062. So I assume the structure of the assignment is outdated and is suitable only for the version of the project that existed on edison.mit.edu.

**Comment by ald32** [comment]
I forgot to follow up with you on this issue. Does this mean that the information for this assignment is still contained within the code, but we can't access it? Would we be able to re-make the assignment at some point? Perhaps once the instructor account is set up and running?
Thanks,
Alison.

**Comment by annagav** [comment]
Try redefining the assignment builder.
