### ISSUE TITLE
Investigate and remove unneeded dependencies

### ISSUE THREAD

**Issue by carsongee** [starteam/starcellbio_html#139]
As noted in #129 

> while we're at it, is django-bootstrap-form, django-filter, django-tastypie, or djangorestframework even used? I also find it very strange that we have both of the two major competing API libraries (tastypie and DRF).

There are probably other python packages outside of these that need to be upgraded and/or removed

**Comment by annagav** [comment]
The following packages are optional for django rest framework:
-Markdown - Markdown support for the browsable API.
-django-filter  - Filtering support.

**Comment by annagav** [comment]
Fixed by #144.
