### ISSUE TITLE
NSF - Exercise 3: Make image within the "Introduction" clickable to view full size

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#148]
Is it possible to make be able to click on the image within the "Introduction" blurb and have it pop into a new window where one can see the full size image? It is really hard to see details in the current state.

**Comment by annagav** [comment]
Better resolution image: StarCellBio --> Curriculum --> Lisa's exercises --> exercise 3 --> images --> egfr pathway drawings

**Comment by annagav** [comment]
first let's try to replace the image. Might be enough.

**Comment by pdpinch** [comment]
I'm not sure where to find this...
