### ISSUE TITLE
As student using Western Blot, band intensity should change when slider is moved NSF - Exercise 3

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#149]
The band intensity does not increase or decrease as one moves the "Exposure time" slider right or left, respectively. 

https://starcellbio.mit.edu/#experiment_id=scb_Experiment_c0m60q1cp526f&assignment_id=scb_ex3&western_blot_id=scb_WesternBlot_7nli4629382ac&western_blot_gel_id=scb_WesternBlotGel_163ip8820gago&view=western_blot_gel&skip_hash_update=false

**Comment by annagav** [comment]
@laleman, the way the code was written is that if there is no intensity given, e.g. intensity is 'none', band doesn't change. Does the band size not change even for the samples for which the intensity was specified in the coding for the assighment?

**Comment by ald32** [comment]
@annagav - if no intensity is given, then that means that a band shouldn't appear at all. 'None' means that the sample won't have a band with that particular antibody. In addition, the intensity, when specified, (for example: medium, high, low) is in reference to the intensity of the band at 1 minute, which is the default exposure time. The exposure should then change when the exposure slider is moved to shorter or longer time periods.
In Exercise 2 and 3, the coding for the western blot has many incorrect bands. I believe that this could be that bands are appearing even when there isn't supposed to be a band. I will make a detailed github comment now for Exercise 2, but I haven't gone through Exercise 3 in detail yet. Does my comment about 'none' referring to no band at all clarify the coding of the western blotting or is it unrelated?

**Comment by annagav** [comment]
ok, I will make sure that bands do not appear with intensity is 'none'. Please let me know if the rest of the bands with some intensity don't change size with the change of exposure time.

**Comment by ald32** [comment]
All of the bands (regardless of starting intensity) should change when the exposure time is changed.

**Comment by annagav** [comment]
Sorry, I meant if band change is currently working on scbdev for bands with intensity ('low', 'med','high').

**Comment by ald32** [comment]
I don't see any bands changing in intensity right now in exercise 2 when I adjust the exposure slider.

**Comment by pdpinch** [comment]
Should also be fixed by #267

**Comment by ald32** [comment]
The exposure time slider does seem to be working now and adjusting the band intensity appropriately. I will close this now.
