### ISSUE TITLE
NSF Exercise 2 - Assignment text edits

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#151]
Here are a couple of edits to be made to the assignment text. I am grouping them together as they are fairly minor, but let me know if you would like me to separate them for you.
1. Numbers that correspond to the footnotes should be superscript, not preceded by ^. There are several numbers within the Background tab that are not superscript.
2. There is extra text that appears in a few locations 'Ver. 10 - L. Weingarten'. I'm not sure why this text is appearing, but I saw it in a couple of places in the Background tab (within the Cell Lines and Flow Cytometry tables).

**Comment by ald32** [comment]
@ annagav - I mentioned some of these errors in more detail in a new issue that I did today. Sorry I have replicated the issue now.

**Comment by pdpinch** [comment]
This has been merged, but it hasn't been released to the development server yet.

**Comment by ald32** [comment]
I'm going to close this one as there's another issue that is more detailed regarding the assignment text changes.
