### ISSUE TITLE
Setup page - Add Samples pop up window should have select all and clear all buttons (NSF Exercises 2 & 3 - & all exercises)

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#154]
The pop up add samples window should have a 'SELECT ALL' and 'CLEAR ALL' buttons. The select all button appears below the checkboxes. The clear all button should be on the right side of the window, vertically aligned with the select all button. See the table in the flow cytometry technique as an example: https://scbdev.odl.mit.edu/#view=facs&experiment_id=scb_Experiment_1g0b00e19oq6im&assignment_id=scb_ex2&facs_id=scb_Facs_73pk9728768a1

**Comment by ald32** [comment]
@pdpinch - This isn't marked for review, but I think it can be closed.

**Comment by pdpinch** [comment]
Excellent. Thank you.
