### ISSUE TITLE
NSF Exercise 2 - Edits to Strain names in the Add Samples pop up window

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#155]
The Strain in the Add samples window should be: His-ProX-FLAG and His-ProY-FLAG. There is a missing hyphen in the pop up window, but it later appears correctly once the samples have been added to the experiment.
https://scbdev.odl.mit.edu/#view=experiment_setup&assignment_id=scb_ex2&experiment_id=scb_Experiment_1g0b00e19oq6im

**Comment by pdpinch** [comment]
:100:
