### ISSUE TITLE
NSF Exercises 2 & 3 (and all exercises) - Format the Add Samples pop up window

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#156]
Move the Strains and Treatments columns over to the left to remove some of the space between the checkboxes and the first column.

**Comment by annagav** [comment]
<img width="622" alt="screen shot 2016-10-14 at 3 54 54 pm" src="https://cloud.githubusercontent.com/assets/7574259/19400835/104887a2-9226-11e6-8282-4fd8029dfe4d.png">
