### ISSUE TITLE
NSF Exercises 2 & 3 (and all exercises) - Western blotting load gel page - The up and down arrows to organize samples are offset

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#158]
The up and down arrows to organize the samples are offset from one another.
https://scbdev.odl.mit.edu/#view=western_blot&experiment_id=scb_Experiment_1g0b00e19oq6im&assignment_id=scb_ex2&western_blot_id=scb_WesternBlot_pl75361adm017

**Comment by annagav** [comment]
@ald32 Should they be the same height and symmetrical?

**Comment by ald32** [comment]
Yes the same height and symmetrical would be great! thanks!
