### ISSUE TITLE
NSF Exercise 2 - Errors in western blotting bands

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#161]
The bands are not appearing correctly on the western blot:
PGK1 should produce bands in every lane at 44 kDa.

Protein X antibody should detect bands at 82 kDa (low intensity) in 'No tags growth media', 'ProY null growth media', 'His-Prox-FLAG growth media', 'His-ProY-FLAG growth media'. Also at 84 kDa with high intensity in 'His-Prox-FLAG growth media'.

Protein Y antibody should detect at 230 kDa low intensity in 'No tags growth media', 'ProX-null growth media', 'His-ProX-FLAG growth media', 'his-proY-FLAG growth media'. Also at 232 kDa high intensity in 'his-proY-FLAG growth media'.

6xHis antibody should detect at 84 kDa (high intensity) in 'his-prox-flag growth media', 40 kDa (med intensity) in 'his-prox-flag growth media+prok', and 232 kDA high intensity in 'his-proy-flag growth media'.

anti-flag antibody should detect at 84 kDa (high intensity) 'his-prox-FLAG growth media' and 232 kDa high intensity in 'his-proy-flag growth media'.

The intensity mentioned above (high, medium, low) refers to the intensity of the band at the default exposure time, which is 1 minute.

**Comment by pdpinch** [comment]
will be fixed by #267

**Comment by ald32** [comment]
Some of the bands are still off. 

PGK1 should produce bands of equal intensity for all samples, but I see a significantly less intense band in the 'ProY-Null, Growth Media + ProK' sample.

The protein X antibody should detect two bands, one at 82 (low intensity) and one at 84 (high intensity), in the 'His-ProX-Flag, Growth Media + buffer' sample, but I only see the band at 84 kDa.

The protein Y antibody should detect a low intensity band at 230 kDa in the 'His-ProX-Flag, growth media + buffer' sample, and 2 bands (one low at 230 and high at 232) in the 'His-ProY-Flag, growth media + buffer' sample.

The anti-6xHis antibody is detecting the bands at the correct sizes but wrong intensities. It should be a high intensity band at 84 kDa in 'his-prox-flag growth media + buffer', a medium intensity band at 40 kDa in 'his-prox-flag growth media+prok', and a high intensity band at 232 kDA in 'his-proy-flag growth media + buffer'.

**Comment by annagav** [comment]
For anti-6xHis antibody is this incorrect?
![screen shot 2015-07-30 at 3 19 32 pm](https://cloud.githubusercontent.com/assets/7574259/8992793/8d8e1858-36ce-11e5-8d7a-39d3facaeb8e.png)

**Comment by ald32** [comment]
Yes that looks great!

**Comment by ald32** [comment]
The 6xHis antibody looks better but the other antibodies still have the errors described above. @annagav

**Comment by ald32** [comment]
I would like to increase the gap between the bands that appear at 82 and 84 kDa with the Protein X antibody so you can more easily see that there are two bands appearing. (I would like it to look like the Protein Y antibody where you can more easily see that there are two bands). All the other bands look great.

**Comment by pdpinch** [comment]
could try increasing the difference between the bands to 5 kDA

**Comment by pdpinch** [comment]
Will need review after deployment to scbdev
