### ISSUE TITLE
NSF Exercise 2 - Flow cytometry setup page

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#163]
The setup table needs to allow each sample to be analyzed by more than one condition (like the microscopy experimental technique, when applicable). This will correspond to more tabs in the small tabbed window for each sample once the user gets to the flow cytometry run/analyze page. Once a condition is selected, another 'select condition' drop down menu will appear below it in the same row (within the black horizontal lines). Subrows for a sample are divided by a light gray line. Like in the 7.06 exercise:
https://starcellbio.mit.edu/#view=microscopy&experiment_id=scb_Experiment_mf96aa1ogjgj3&assignment_id=assignment_706_2014_ps2&microscopy_id=scb_Microscopy_1896mm1c52jfp

**Comment by annagav** [comment]
I have discussed this with Lourdes back in November/December, and she proposed to allow only one condition pick per sample per experiment.

**Comment by ald32** [comment]
I didn't realize that. How hard would it be to change the coding of flow cytometry to match that of the microscopy technique (where you can have more than one condition per sample and multiple small tabbed windows appear)?

**Comment by annagav** [comment]
It depends on the current state of the code. :-)

**Comment by ald32** [comment]
As we talked about in our meeting last week, implementing this change will be really useful and necessary. Making the change will also make this experimental technique align with the plans for the assignment builder.

**Comment by ald32** [comment]
I think we need to add trash can icons to the samples in this page so users can remove a sample if they no longer want it. (Exercise 3 already has this on the microscopy setup page.)

**Comment by ald32** [comment]
Is there a way to format the radio buttons to conserve space in exercises 2 and 3? I'm wondering if we can put more than one radio button per line so that the list does not grow to be so big. Also, are there any ways that you can think of to easily add all conditions for each sample? I'm thinking of a checkbox somewhere where you can select all conditions for a particular sample.

**Comment by annagav** [comment]
I can arrange 2 conditions per line. Would you like the number of conditions per line to depend on the length of the condition name? 

I can make a checkbox that would create lanes for all conditions for this sample, but that would list all the lanes for that sample. It will make it easier to select all conditions but it would not shorten the length of the list.

**Comment by ald32** [comment]
Two conditions per line would be great and/or depending on the length of the condition name.

Could we add a column to the right of the conditions where we can have a checkbox that says something like "add all conditions"? I'm not sure what this would look like, but it's an idea as a lower priority item.

**Comment by pdpinch** [comment]
Trash cans have been merged.

@annagav what's the plan for displaying multiple condition radio buttons per line?

**Comment by annagav** [comment]
Should we keep this within this issue? 
I think first priority will be to add a "select all condition" checkbox. And then I will put two conditions per line.

**Comment by pdpinch** [comment]
I created two new issues as recommended by @annagav #313 and #314 regarding the layout of the conditions. 

This issue is now ready for review by @ald32 and/or @laleman

**Comment by ald32** [comment]
The trash can icons are working appropriately. (I'm not sure if that's what I am supposed to review?)

**Comment by pdpinch** [comment]
That's what I was looking for. Thanks. 

(Sorry this issue got a little overloaded).
