### ISSUE TITLE
NSF Exercises 2 & 3 - Peaks on the flow cytometry analyze page

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#164]
I'm expecting the graph 'C' on the coding document to have a higher peak. The area under the curve should be comparable to the the area under curves A and B (as specified in the coding document). Can it extend up on the y-axis further?
https://scbdev.odl.mit.edu/#view=facs&experiment_id=scb_Experiment_217538o22fca5e&assignment_id=scb_ex2&facs_id=scb_Facs_1lj7bc025ap202

**Comment by ald32** [comment]
I have edited the title to indicate that this also applies to Exercise 3 as well as Exercise 2.

**Comment by pdpinch** [comment]
Try to make it closer to 55-60 on the y-axis, with the same area under the graph. 

Other peaks could be made taller, 85-90.
