### ISSUE TITLE
NSF Exercises 2 & 3 - Analysis tools in the flow cytometry technique - Apply all button isn't working

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#166]
The apply to all button doesn't appear to be working. When selected, I don't see the histograms on the other graphs.

This may also apply to NSF Exercise 3, but I haven't had a chance to check yet.

**Comment by ald32** [comment]
This does apply to NSF Exercise 3, in addition to Exercise 2. I have updated the title to reflect this.

**Comment by ald32** [comment]
In Exercise 2 (when I have multiple samples each with 4 flow cytometry conditions), when I click "Apply to all", the gate(s) are only added to the first tab of the first sample.

**Comment by ald32** [comment]
When I use the Apply to All button in Exercise 3, it also only applies the gates to the first sample (although in this exercise there is only one tab/condition per sample).

**Comment by annagav** [comment]
This PR has not been merged yet. But I checked in Exercise 2 'apply to  all' works across tabs.

**Comment by ald32** [comment]
ok great!
