### ISSUE TITLE
NSF Exercise 3 - western blot bands are incorrect

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#169]
I haven't gone through all of the bands in detail, but bands are appearing where there shouldn't be any bands. For example, the WT EGFR sample with the FLAG or His antibodies should be blank. @annagav, would you like to go through the coding Excel spreadsheet together?

**Comment by ald32** [comment]
The "NoUB growth media + EGF, 6 hours" (sample 6) band for the pEGFR blot looks like a higher intensity than the samples around it. The sample should have a high intensity, which should be the same as samples 5-12 whereas sample 4 should have a medium intensity. Also the band is slightly high here as it appears close to 150 kDa, but should be 140 kDa.
![screen shot 2015-07-28 at 4 07 58 pm](https://cloud.githubusercontent.com/assets/1855065/8942405/2888e294-3543-11e5-92d9-b7de75de50fa.png)

**Comment by ald32** [comment]
The bands for pRAF are lower than they should be and the pMEK bands are much higher than they should be. I think these bands are switched actually as they are in a different order on the Excel coding sheet than in the small tabbed windows in StarCellBio. Can you please check the bands for these two antibodies and confirm they are switched?
The 51 kDa band for "His-EGFR-FLAG, Growth media + ProK 30 min" on the FLAG blot appears much higher than the 51 kDa band for the His-EGFR-M2-FLAG, Growth Media + ProK 30 min" sample.

**Comment by annagav** [comment]
pRAF and pMEK are switched. I will fix this in the next PR. 
The weights for the bands "His-EGFR-FLAG, Growth media + ProK 30 min" and "His-EGFR-M2-FLAG, Growth Media + ProK 30 min" seem to be the same number as in the coding of the exercise. They do appear to be a little off, but I thought it was by design, to give a little randomness to the output.

**Comment by ald32** [comment]
@annagav - Are the updates to these bands in the latest release?

**Comment by pdpinch** [comment]
They are not in this release, sorry. 

I should have removed the "Needs Review" label.

**Comment by ald32** [comment]
The anti EGFR, pEGFR, PGK1, 6xHis, and FLAG bands are all correct.
In the pRAF blot, the 'EGFR-M2, Growth Media + EGF 30 sec' should be medium intensity and the 'EGFR-M2, Growth Media + EGF 1 min' and 'EGFR-M2, Growth Media + EGF 6 hrs' should be high intensity (I think these samples are switched - 30 sec looks like high intensity and the other two look medium intensity to me right now). All other pRAF bands are correct.
