### ISSUE TITLE
NSF Exercise 3 - Change scroll bar in Samples window on Flow Cytometry Analyze page

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#171]
The scroll bar should always be visible to indicate to users that there are more than 12 samples (like the samples window on the load/analyze page of the microscopy experimental technique). In addition, the scroll bar should appear further over to the right so that it doesn't overlap the name of the sample.
https://scbdev.odl.mit.edu/#view=facs&assignment_id=scb_ex3&experiment_id=scb_Experiment_56j9bo28ea87j&facs_id=scb_Facs_j7im5mibq9dn

**Comment by annagav** [comment]
@ald32, Would you like the scroll bar to be visible everywhere, e.g "add Samples" window or assignments text, or just specifically this case?
