### ISSUE TITLE
As student in microscopy, need a way to navigate the small tabbed windows on Analyze page

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#173]
I set up a microscopy experimental technique with 6 conditions for three of my samples, but only 4 small tabbed windows appear on the analyze page of the microscopy experimental technique. We need a way to navigate the small tabbed windows on the analyze page of this technique - just like in the western blotting technique when you re-probe with many antibodies.

https://scbdev.odl.mit.edu/#view=microscopy&experiment_id=scb_Experiment_56j9bo28ea87j&assignment_id=scb_ex3&microscopy_id=scb_Microscopy_1j7nd355m6old

**Comment by pdpinch** [comment]
This should be done the same way as it's done in Western Blotting.

**Comment by pdpinch** [comment]
@ald32 @laleman can you confirm this is working as expected on https://scbdev.odl.mit.edu/

**Comment by ald32** [comment]
The arrows & their hover states are working appropriately. We would like it to remember which tab the user was viewing when switching between samples however. Can you remember this information for the user?

**Comment by ald32** [comment]
Working great!
