### ISSUE TITLE
NSF Exercise 3 - If there is only one Microscopy analysis on the setup page, then make it the default (no dropdown menu needed)

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#174]
As there is only one microscopy analysis (Antibody-labeling IF) for each sample on the sample prep page, then the dropdown menu isn't needed. We can make the analysis the default. The text 'Antibody-labeling IF') should appear in black text once the sample is selected.

https://scbdev.odl.mit.edu/#view=microscopy&assignment_id=scb_ex3&experiment_id=scb_Experiment_56j9bo28ea87j&microscopy_id=scb_Microscopy_4oe44528ib8ap

**Comment by annagav** [comment]
This assignment '__assignment_706_2014_ps2' has the same behavior. Should I modify overall behavior  when having one analysis type?

**Comment by annagav** [comment]
Also,  when you select analysis, even if it is only one, it adds the next 'empty' row for the same sample to select another condition. If I remove this select menu, I am not sure on what event to add another row.

**Comment by ald32** [comment]
Yes we should modify this behavior for all assignments (even the old 7.06 assignment that you mention above). We can add a new row once a condition is selected, instead of once an analysis is selected. This aligns with the correct hierarchy of analysis -> condition.

**Comment by annagav** [comment]
Fixed by #190.

**Comment by ald32** [comment]
This is working in NSF Exercise 3, but I haven't checked the old exercises yet.

**Comment by annagav** [comment]
Checked SUTD assignments.
