### ISSUE TITLE
NSF Exercise 3 - Microscopy images won't load for the 3 EGFR Null samples

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#175]
The microscopy images aren't loading for the 3 EGFR null samples. The 'In the Lab' video also isn't re-loading when I select these samples as well. (The 'In the lab' feature video reloads every time I change samples).

https://scbdev.odl.mit.edu/#view=microscopy&experiment_id=scb_Experiment_56j9bo28ea87j&assignment_id=scb_ex3&microscopy_id=scb_Microscopy_1j7nd355m6old

**Comment by ald32** [comment]
I just realized that these images are supposed to have a black square, which is why the viewfinder appears black. How can we indicate to students that an image has loaded, but that there is nothing there? Also, the in the lab video didn't re-load, so I thought there was something wrong.

**Comment by annagav** [comment]
When you load the images a small window appears that covers the microscope, saying that images have been loaded, right? I thought that is the purpose of that window.

**Comment by pdpinch** [comment]
Can this be closed, or do we need a ui change to alert the user that the image has been loaded?

**Comment by pdpinch** [comment]
This may be fixed after #194 is merged.

**Comment by pdpinch** [comment]
closed via #194
