### ISSUE TITLE
NSF - Exercise 3: Assignment's page missing the "Print" icon and associated PDF

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#180]
Exercises 1 and 2 have small icon at the bottom left corner of the assignment text window. If you click on this icon, it will take you onto the PDF version of this assignment. This is missing in Exercise 3. The PDF associated with this exercise can be found here:

https://www.dropbox.com/s/q8vi4og3h5piila/SCB%20Exercise%203_ver17_questions.pdf?dl=0

Here is a picture of what the icon looks like for Exercises 1 & 2:

![screen shot 2015-04-27 at 2 33 50 pm](https://cloud.githubusercontent.com/assets/11359229/7354598/7983406e-ecea-11e4-97a0-a42b2ca55e67.png)

**Comment by ald32** [comment]
I have moved this up to Medium priority so that this exercise matches the other two NSF exercises.

**Comment by pdpinch** [comment]
This has been merged, but it hasn't been released to the development server yet.
