### ISSUE TITLE
NSF - Exercise 3: Flow Cytometry Set Up page, the "Flow Cytometry Analysis" label remains graded out even after a sample has been selected

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#184]
In the Flow Cytometry Set Up page, the "Flow Cytometry Analysis" remains graded out until a Condition is chosen, even if the sample has been already selected and there is only one flow cytometry analysis (antibody-labeling) available in this particular exercise. 

![screen shot 2015-04-27 at 3 10 05 pm](https://cloud.githubusercontent.com/assets/11359229/7355503/5be9c5e0-ecf0-11e4-906a-52dacdd0a88f.png)

**Comment by laleman** [comment]
Oops, I just realized that Alison already submitted this bug.

**Comment by ald32** [comment]
This has been fixed. I am closing this issue.
