### ISSUE TITLE
As instructor, I can create a new course

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#199]
> Within the assignment builder, instructors will be able to create or edit existing assignments that students can then access through their student accounts. In this screen, instructors can create a new course or select an existing course to add a new assignment to. If the course is new, instructors can provide the name of the new course and its associated course code. The must up-to-date mockup of the course setup pages is in the mockup version of the assignment builder located in: scbdev.mit.edu. A screenshot of what that looks like is provided:
> 
> Supporting documentation see: starcellbio_html repository docs/Evernotes/Combined Notes on the Assignment Builder.pdf
> docs/ScreenShots/AssignmentBuilder_Course_Screen.png

**Comment by pdpinch** [comment]
May need some more discussion with Alison.

**Comment by ald32** [comment]
After seeing a few recent comments about the assignment builder, I am wondering if we should gather some feedback on our paper prototypes/wireframes and/or initial prototype. We can discuss more at our next meeting.

**Comment by ald32** [comment]
I'm ok with closing this issue with the solution that we currently have. @pdpinch @annagav
