### ISSUE TITLE
As instructor, I can choose combinations of analysis/condition for microscopy technique

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#201]
[Pages from SCB_ProblemSetBuilder_09_Microscopy.pdf](https://github.com/starteam/starcellbio_html/files/188215/Pages.from.SCB_ProblemSetBuilder_09_Microscopy.pdf)

> In this page the instructor will select the microscopy analysis and associated conditions that are available for each sample. All microscopy analysis/conditions previously specified in Page 1 are automatically selected for each sample. In this page the instructor can unselect any combination of analysis/condition that does not apply for a given sample.
> 
> starcellbio_html repository docs/problemsetbuilder/User Interface Design Documents - Jamie Waters/SCB_ProblemSetBuilder_09_Microscopy.pdf  the question text on page 4 in 'SCB_ProblemSetBuilder_09_Microscopy.pdf has been updated. For the updated question wording, please see the design sketch document, 'Instructor Account UI - Microscopy Ver5.pdf'
> 
> starcellbio_html repository docs/problemsetbuilder/User Interface Sketches/Microscopy/Instructor Account UI - Microscopy Ver5.pdf  notes on the functionality required in each step to set up the microscopy experimental technique. Notes on each step are in blue text. However, design elements and layout have been modified by the graphic/user interface designer. In these cases, defer to the graphic designer document, listed above.

**Comment by pdpinch** [comment]
@annagav what's the status of this issue? Is this the one that needs to be reviewed?

**Comment by annagav** [comment]
In one of the meetings with Lourdes and Alison we decided to skip this page. If the instructor does not have an image for a sample then he can just leave it empty (with no images) in the 'analyze' page.
