### ISSUE TITLE
As instructor, I can upload microscopy images corresponding to specific analysis/conditions

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#202]
> In this page the instructor will upload the image(s) associated with each sample and its corresponding microscopy analysis/conditions. Once the instructor clicks “Add Image(s)” a pop up window will appear where the instructor can select an image from his/her computer. (see the StarCellBio AssignmentBuilder – Microscopy Page 4). Once an image is selected/uploaded the instructor can apply the image(s) to other samples. For any given image the instructor has the option of specifying the microscope objective used to obtain the image.
> 
> starcellbio_html repository docs/problemsetbuilder/User Interface Design Documents - Jamie Waters/SCB_ProblemSetBuilder_09_Microscopy.pdf  the question text on page 4 in 'SCB_ProblemSetBuilder_09_Microscopy.pdf has been updated. For the updated question wording, please see the design sketch document, 'Instructor Account UI - Microscopy Ver5.pdf'
> 
> starcellbio_html repository docs/problemsetbuilder/User Interface Sketches/Microscopy/Instructor Account UI - Microscopy Ver5.pdf  notes on the functionality required in each step to set up the microscopy experimental technique. Notes on each step are in blue text. However, design elements and layout have been modified by the graphic/user interface designer. In these cases, defer to the graphic designer document, listed above.
> 
> The graphic designer did not detail each step of setting up a microscopy experimental technique. In total there are 3 questions/steps to set up a microscopy experimental technique, and the designer sketched out steps 2 and 3. For step 1 (question wording and answer choices), please see the design sketch document, 'Instructor Account UI - Microscopy Ver5.pdf'.

**Comment by pdpinch** [comment]
@annagav after #652 and #657 merged, what more needs to be done here? (It seems like this story is maybe too big)

**Comment by annagav** [comment]
Copy images to other samples would be another functionality. But could be in different issue.

**Comment by pdpinch** [comment]
Closing this. Remaining work is now in #703
