### ISSUE TITLE
As instructor, I can edit the objective information for any microscopy image

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#204]
> This page shows how Page 3 within the Microscopy section of the Assignment Builder will appear once images have been added using the pop-up window in Page 4. Thumbnails of uploaded images are shown underneath its corresponding sample. Users should be able to delete images that have already been uploaded, add more images to a given sample, and edit the objective information for any given image.

**Comment by annagav** [comment]
It is not relevant anymore.
