### ISSUE TITLE
As an instructor, I can edit an assignment

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#211]
In the current design documents, it's not clear how to change the name of an assignment.

**Comment by annagav** [comment]
Also, course_name and course_code for that assignment.

**Comment by ald32** [comment]
Hi Peter,

This information is included in the Evernote list. I have pasted the relevant section below. Once an instructor selects "Create a New Assignment" on the dashboard, then the first page of the problem set builder contains text boxes where the instructor can select the name of the assignment, course, and course code. Also, an instructor should be able to navigate back through all of the pages of the problem set builder so the instructor can go back and change these values easily.

Assignment/Course Setup
The best current mock-up of the assignment/course setup pages is in the current version of the assignment builder (scbdev.mit.edu). The questions and how they appear are correct based on our design. 

Notes:
Once an instructor selects 'Create a New Assignment +', the instructor will be taken to the first couple pages of the assignment builder where s/he will specify details for the assignment such as the course name, course code, assignment name, etc.
An instructor can either set up a new course or add an assignment to an existing course. 
The instructor can then select whether s/he would like to start a completely new assignment or use another assignment as a template. 
After these steps, then the instructor will be taken to the first page of the experiment setup.
We also agreed that an instructor will be able to navigate backward in the process and edit things. If the instructor edits options/dropdowns/text boxes, etc. then a warning will appear saying that the instructor may lose information that has already been set on later pages. As a result, 'Back' buttons need to be added to all of the assignment builder pages in the lower left corner.
