### ISSUE TITLE
NSF Exercise #1 - Formatting the Add Samples window

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#218]
The 'CANCEL' and 'ADD SAMPLES' buttons need to be moved to the lower right corner. This will mean that they don't conflict with the 'SELECT ALL' button that will go underneath the checkboxes. This should be the case for all exercises within StarCellBio, not just NSF Exercise #1.

**Comment by ald32** [comment]
Can you switch the placement of the 'Cancel' and 'Add Samples' buttons so that the 'Add samples' button is in the lower right corner?

**Comment by annagav** [comment]
This was already fixed.
