### ISSUE TITLE
NSF Exercise #1 - Microscopy images aren't appearing for 3 samples

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#219]
Microscopy images aren't appearing for 3 samples:

GFP-Mut ProB
GFP-Nuc
GFP-PM

**Comment by annagav** [comment]
Seems like all images appear for me. Maybe other fixes eliminated the problem. Need to test it again in the next release.

**Comment by ald32** [comment]
I still can't see an image for GFP-Mut ProB (or I can't find it!). I can see images for the other two samples.

**Comment by ald32** [comment]
Actually, I just can't see the images for the first microscopy experiment that I had. I can see the image in second and third microscopy experiments.

**Comment by pdpinch** [comment]
Can you be more specific about where the image is missing? Is it loading for you in some cases, but not others?

**Comment by annagav** [comment]
I looked at the images provided for this sample and looks like there is a black image: nucleus_final/n60.jpg. Maybe that is why you don't see anything.

**Comment by ald32** [comment]
Good catch! It's also in the images folder within Exercise 3. I have removed it from both places.

**Comment by ald32** [comment]
There's still a black image in the nucleus folder. I got the black image for the GFP-Nuc sample that is using the images from the same folder. @annagav

**Comment by pdpinch** [comment]
I'm not clear on what needs to be done now with this issue. Is it still open?

**Comment by ald32** [comment]
Yes, this issue is still open. I have removed the wrong image from the folder of images that we have in Dropbox, but the wrong image still needs to be removed within StarCellBio.

**Comment by laleman** [comment]
I just tested this and it looks like an nuclear staining image is appearing for GFP-Nuc which would make it seem like the issue was fixed?

**Comment by ald32** [comment]
The folder contains many images that are correct and only one image that is wrong. So it depends on which image is used for a sample that needs nuclear staining. You must have gotten a correct image.

**Comment by ald32** [comment]
I didn't see any black images where there shouldn't be one. Is there a better way to test that they are no longer appearing though?

**Comment by annagav** [comment]
I don' think there is a better way to test it, other than trying it many times, since it is a random algorithm that picks images from the folder.

**Comment by annagav** [comment]
I don' think there is a better way to test it, other than trying it many times, since it is a random algorithm that picks images from the folder.

**Comment by ald32** [comment]
I just did 4 microscopy exp techniques and all the images loaded appropriately so I think it's working.
