### ISSUE TITLE
NSF Exercise #1 - Laser button should be "on" and light should be "off" in microscopy experimental technique

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#221]
The laser button should default to "on" and the light should be "off"/disabled for all of these samples as they are fluorescent samples and require the laser to be on and the light to be off for the images to be visible. (See Exercise #3 for how this should be). The light on/off switch should actually be disabled so the user can't turn it on and off. Currently in Exercise 3, the light switch appears as if you can turn it on/off until you click on it, then it turns to gray to indicate that the switch is disabled. The light on/off switch should be disabled from the very beginning for both exercises 1 and 3.

**Comment by pdpinch** [comment]
@ald32 can you confirm that this is working as you expect on https://scbdev.odl.mit.edu/?

**Comment by ald32** [comment]
Yes this looks great!
