### ISSUE TITLE
NSF Exercises - checkmark formatting

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#224]
The checkmarks are now being formatted differently than previously. Can you switch it back to the formatting that aligns with the rest of StarCellBio's design?

**Comment by pdpinch** [comment]
I don't suppose you can add before/after screenshots for this? 

Presumably, the "before" state is still available on starcellbio.mit.edu

**Comment by ald32** [comment]
I just checked out the promotional video that we have on the SCB homepage and realized that we used to use the default apple checkmarks. But they look different to me on my brand new computer. As a result, we can disregard this issue!
