### ISSUE TITLE
NSF Exercises 1 & 3 - the hand cursor should appear when hovering over the microscopy image

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#225]
The cursor should change to the hand cursor when the user is hovering over the microscopy image in the microscope's viewfinder. This will indicate to the user that s/he can drag the image in the viewfinder to get a better look at it.

**Comment by ald32** [comment]
The hand cursor does appear when hovering over the microscope viewfinder, but it can be hard to find the image within the viewfinder, especially if the image has a black background and the cell is not visible. I cannot find the image for "GFP-Mut ProB" in NSF Exercise 1. I think it used to appear as the hand cursor only when hovering over the confines of the image within the viewfinder. Is there anything we can do to make moving the image into the center of the viewfinder easier for our users?

**Comment by pdpinch** [comment]
@ald32 would you like the images to be centered in the viewfinder when they load?

**Comment by ald32** [comment]
No we would prefer for them to be randomly positioned so that the students need to find the image, as they would have to in a real laboratory. However, we do need to make sure that a small area of the image is visible in the viewfinder so the user can easily find and center the image.
