### ISSUE TITLE
Labeling of the small tabbed windows in the microscopy exp tech

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#226]
We should come up with a consistent labeling method for the small tabbed windows within the Load/Analyze pages of the microscopy experimental technique. If all three filters are being used, then the name can be quite long. In the past, we have done 'R:X G:GFP B:DAPI' with a very short description of the following each of the R, G and B. 

In NSF Exercise 1, we can label the tab as 'G:GFP'.

**Comment by annagav** [comment]
For these exercises I found different labelings:
706_ps2  -                    'R:γ-tub, G:α-tub, B:DAPI'
microscopy_usability -  'R:Nfib, G:control, B:DAPI'.

Do they mean the same thing?

**Comment by ald32** [comment]
They both are using the same nomenclature for labeling. The labels for each of the three channels (Red (R), Green (G), and Blue (B)) are the same, but the proteins/antibodies/stains that are in the red and green channels are different.

**Comment by ald32** [comment]
They're labeled appropriately in the NSF exercises, but I haven't checked the other exercises yet.

**Comment by annagav** [comment]
Looks good in SUTD exercises.
