### ISSUE TITLE
"In the Lab" video player should play only one video at a time

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#24]
You can start multiple videos playing at once.

Steps to reproduce:
1. Start an experiment with micrsoscopy
2. Advance to the "Select Technique" tab
3. In the "In the Lab" video player (middle right) press the play button. This should start a video.
4. Advance to the next button using the right-pointing green arrow. This should bring up the YouTube thumbnail from a second video. 
5. Press Play button

expected result: 1st video stops, 2nd video starts
actual result: both videos play at the same time

**Comment by ald32** [comment]
I noticed this too. I can start a video, move to the next video (within the 'In the Lab' features) and the first video will keep playing as the second one starts. @pdpinch - Can this be fixed by the time the first SUTD exercise deploys?

**Comment by pdpinch** [comment]
This will be moot when we fix #59

**Comment by annagav** [comment]
We decided to not play the video within starcellbio. Instead we want to open a new tab for the video. We assume that no one would want to watch a tiny video.

**Comment by annagav** [comment]
Fixes #150
