### ISSUE TITLE
Course Setup: consider warning user when changing course code

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#250]
The course code is the primary key in the course model. So if the user changes the course code, it will change the code for all assignments associated with that course. 

Do we need to warn users when this happens?

**Comment by pdpinch** [comment]
On hold until we meet again with users.

**Comment by annagav** [comment]
I cant rename an existing course. Need to look into that.

**Comment by annagav** [comment]
Allow to change name and course code for existing courses, show a warning:
Changing the course name and/or code will also change the course name and/or code for all existing assignments associated with this course. Would you like to proceed? Yes/No
