### ISSUE TITLE
Western Blot: Adjust position of tab navigation

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#275]
When the user does more than 4 blots in Western Blotting, arrows appear. They should be aligned with the tabs, so there's no whitespace between the tabs and the arrow buttons. 

i.e., not like this (screenshot from NSF #2):

<img width="887" alt="screen shot 2015-07-21 at 11 54 32 am" src="https://cloud.githubusercontent.com/assets/430126/8805555/de68c47a-2f9f-11e5-97e2-bce8759b3922.png">

**Comment by ald32** [comment]
The tabs look great in microscopy, but still need to be adjusted in western blotting.
![screen shot 2015-07-28 at 3 37 51 pm](https://cloud.githubusercontent.com/assets/1855065/8941629/a6a13a8c-353e-11e5-80cb-8beb976109c6.png)

**Comment by laleman** [comment]
Still do not look right for me. Here is NSF Exercise #2
![screen shot 2015-08-12 at 4 46 13 pm](https://cloud.githubusercontent.com/assets/11359229/9236254/b0a9648a-4111-11e5-973c-783613acc6e5.png)

**Comment by pdpinch** [comment]
Sorry, this fix didn't make it on to the development server yet. I'll remove the Needs Review label until it has.
