### ISSUE TITLE
NSF Exercise 3 - Change label of small tabbed window in flow cytometry

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#290]
The label on the small tabbed window reads "PI" in gray when you get to the "Run" page of the flow cytometry experimental technique. Once you click "Run samples" then the label of the small tabbed window changes to what it should say, which is "EGFR A488".

**Comment by annagav** [comment]
@ald32, It seems to be working as you described above. Were you seeing different behavior?

**Comment by ald32** [comment]
Oh my comment above isn't clear. It shouldn't say PI when you first get to the page. It should say "EGFR A488" in gray.
