### ISSUE TITLE
NSF Exercise 3 - Microscopy small tabs are in different order between samples

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#291]
The order of the small tabs is different for WT-EGFR sample at 30 seconds, compared to the WT-EGFR sample at 1 minute and 6 hours. The order should be the same as on the microscopy set up page which means that it should be: EGFR, PM, Cyto, Nuc, ER, and NM. The order of the last two tabs needs to be changed for the 30 second sample.

**Comment by annagav** [comment]
@ald32, I think the tabs appear in the order the user has selected them. Should the order be the one in which instructor enters the conditions?

**Comment by ald32** [comment]
Oh yes, you are correct. I now remember that there was one experiment where I didn't select the conditions in order by mistake. Leave it as is. I will close this issue.
