### ISSUE TITLE
Add new western blotting animations to the Western blotting 'In The Lab' Feature

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#306]
There are three new western blotting animations to be added to the 'In the Lab' feature on the western blotting pages. 

Part I: https://youtu.be/Xs9z8Zy3hv8?list=PLZhxzzyMIQIHhQ2TOGm3HNLA04ZsTmOLW
Part II: https://youtu.be/A7HdGFl22ws?list=PLZhxzzyMIQIHhQ2TOGm3HNLA04ZsTmOLW 
Part III: https://youtu.be/iFxiXlh29Xc?list=PLZhxzzyMIQIHhQ2TOGm3HNLA04ZsTmOLW

This means that there will be 5 items in the "In the Lab" feature on this page. They should appear in the following order:
1) image of a gel
2) Western blotting animation Part I
3) Western blotting animation Part II
4) Western blotting animation Part III
5) In the Lab - Western Blotting

**Comment by ald32** [comment]
I can see all 5 animations and scroll through them as expected. But I started the first western blotting animation (part I) and I noticed that the thumbnail of the animation moved to the right. I also got the part I animation and the In the Lab video playing at the same time. And I couldn't figure out how to stop the animation playing.

**Comment by pdpinch** [comment]
steps to reproduce
1. Advanced to 2nd item (1st video)
2. Click play
3. audio says it's play 1st video, but thumbnail is from last video

**Comment by annagav** [comment]
@ald32, It seems that the problem appears only when you navigate to the video through the circles underneath the video. I also noticed that in microscopy the circle are not clickable. Can I do the same for western blot, or do we want the navigation through the circles be present everywhere?

**Comment by ald32** [comment]
@annagav, If possible, it would be great if you could use the circle at the bottom for all animations. Is that possible?

**Comment by pdpinch** [comment]
@ald32 I've discussed this with Anna and we need to cut our losses here in order to get a bug-free version out to production. For now, we'll disable the circles so users can see them but they can't click on them. 

I'm going to close this issue, after we've released the reverted change, and open a new one for the specific issue of the circle navigation.

**Comment by pdpinch** [comment]
I opened #346 to keep track of the "circle" navigation issue.

**Comment by ald32** [comment]
This sounds like a good solution!
