### ISSUE TITLE
NSF Exercises - Errors in assignment text

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#312]
Exercise 2: 
1) 'Ver. 10 - L. Weingarten' mistakenly appears and should be removed in the His-ProX-Flag row of the 'Cell Lines' table within the Background information tab.
2) The number 2 should be superscript (instead of ^2) in two places within the Western blotting table in the Background information tab: rabbit anti-mouse HRP and goat anti-rabbit HRP rows.
3) 'Ver. 10 - L. Weingarten' mistakenly appears and should be removed in the His A488 row of the 'Flow Cytometry' table within the Background information tab.
4) There are four cases where numbers (3 & 4) should be superscript within the flow cytometry table in the background information tab. 
5) In question 5, a) and b) should be inset to match the a's and b's in other questions. This will mean that the i. and ii. and iii. will need to be inset further underneath a).

Also, can you do a search to make sure that I have found all cases of 'Ver. 10 - L. Weingarten' in the assignment text? This shouldn't be in the assignment text at all.

Exercise 3:
1) In Question 5 b), the period (and space?) at the beginning of the question should be removed.

**Comment by annagav** [comment]
I have already removed 'Ver. 10 - L. Weingarten'  from exercise 2, but I think this change was not included in the release.

**Comment by pdpinch** [comment]
This hasn't been released to the development server yet.

**Comment by ald32** [comment]
For #4 in Exercise 2 above, I think the last number was accidentally switched to a 2 instead of a 3.
I don't see the edit for #5 in Exercise 2 above.
Everything else looks great!
