### ISSUE TITLE
Flow cytometry setup page: add a "select all condition" checkbox

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#313]
As a user, I would like a way to select all conditions in the flow cytometry setup screen, instead of having to click a radio button for each condition.

**Comment by ald32** [comment]
Yes I agree. I have added an issue for the same issue with the microscopy experimental technique, and it would be great to implement the same thing in flow cytometry as well.

**Comment by ald32** [comment]
The 'Add All' button works great and as expected. I feel like there should be some way to indicate that the button doesn't work when all of the conditions have been added. I was originally envisioning a checkbox, but I'm ok with leaving it as a button.  It would be great if you get the pointer cursor when hovering over the button.
