### ISSUE TITLE
Microscopy set up page: 2 conditions per line

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#322]
Because this is mentioned in another issue but doesn't fit with the other issue, I'm creating a new one. As a user, it would be easier to read the microscopy setup page if I could see two conditions per line. This will avoid having to scroll too much.

**Comment by ald32** [comment]
In Exercise 3, I think the trash can icon can be moved over further to the right and we could even fit 3 conditions on one line. In addition, as Peter mentioned, it looks funny when there is only one condition (as in Exercise 1). It would be great if the condition name is always on one line. Can you increase the number of characters that can go on one line so that 'GFP (green)' fits on one line in Exercise 1? We will need to institute a max number of characters for each condition in the assignment builder.

**Comment by annagav** [comment]
We will not be able to fit three conditions per line because there will be a button that adds all conditions, and the trash button will be pushed to the right.

**Comment by ald32** [comment]
Ok
