### ISSUE TITLE
Western Blot: when there are 15 samples, there's no room for a marker

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#328]
> I just added 15 samples to my western blotting exp technique, but then it still let me add the protein marker even though there isn't any available lane for the marker. This then created problems because the colorful marker bands appeared off the gel once I selected 'Run gel & transfer'. 
> 
> If 15 samples are selected on the sample prep page, then the Marker button shouldn't appear in the samples window so students can't even add it to their gels. Also, the colorful bands after selecting 'Run & Transfer' wouldn't appear and the horizontal lines on the side of the blot wouldn't appear.

**Comment by pdpinch** [comment]
@ald32 @laleman would you prefer that we limit the user to 14 samples, leaving room for the marker, or would you prefer that we prevent the marker from being added?

If the latter, should the marker be hidden, or should there be an error message when the user attempts to add it?

**Comment by ald32** [comment]
We would prefer that you prevent the marker from being added. I think the marker button could show but an error message can appear when the user tries to add the marker if the user has already selected 15 samples. Is there already an error message written that we can use? If not, we can write one for you.

**Comment by pdpinch** [comment]
Please do write an error mesage

**Comment by ald32** [comment]
The error message should read:
The marker cannot be added as there is not an available lane to load the marker. The gel only has 15 lanes and one lane should be reserved for the protein marker. 
Ok is the only available choice here. The user would then see the gel with the loaded wells, and can click 'Run Gel &Transfer'. The membrane will appear but without the colorful marker bands and the blot will appear without the sizes on the right side of the blot.

Writing this error message also makes me think that we should add an error message after the user selects 15 samples on the setup page and clicks 'Prepare Lysates'. Can you add an error message there that says:
You have selected 15 samples which means that you have not reserved a lane for the protein marker. The gel only has 15 lanes and one lane should be reserved for the protein marker. Would you like to continue?
Yes/No are the answer choices.

**Comment by annagav** [comment]
@ald32, If you haven't added the marker and clicked LOAD GEL, there is a message saying "The protein size marker has not been added to your samples. Would you like to continue?". It feels a bit contradictory, first I was not allowed to add the marker and then I was told I did something wrong by not adding the marker.

**Comment by pdpinch** [comment]
Suggestion: when there are 15 samples, we should use the "not an available lane to load" error message instead of the "marker has not been added" message.

**Comment by ald32** [comment]
The error message that you mention Anna should not also appear. The only message that should appear is the one that I wrote above. So if you can't add the marker because you have 15 samples, then the user will be told that what they have done isn't ideal, but they can continue. Does that make sense?

**Comment by annagav** [comment]
Do I understand this correctly: 
1. If I have 15 samples
a) I clicked on the marker got the message, 
b) I forgot to click on the marker 
then clicked on LOAD GEL and no message appears.
2. If I have less than 15 samples, and I forgot to add the marker I get the message "The protein size marker has not been added to your samples. Would you like to continue?".

**Comment by ald32** [comment]
@annagav, 1a) and 2 are correct. I am undecided about scenario 1b. Can we talk through it together tomorrow?

**Comment by ald32** [comment]
After discussing this issue with Anna, we came up with a revised plan:
When there are 15 samples, and the user selects 'Prepare Lysates', an error message will appear that says: 
You have selected 15 samples which means that you have not reserved a lane for the protein marker. The gel only has 15 lanes and one lane should be reserved for the protein marker. Would you like to continue?
Yes/No are the answer choices.

If the user continues with 15 samples, then the 'Add Marker' button will appear disabled (grayed out) so the user cannot click on it. When the user selects 'Load Gel', no other error message will appear. The marker will not appear on the gel (no colorful bands), and after blotting with antibodies, the bands will appear for all of the samples, but no size markers will appear at the side of the blot.

**Comment by ald32** [comment]
Looks great!
