### ISSUE TITLE
Get it to run in Heroku

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#331]
as a devops, using Heroku would make continuous integration possible, speeding up development & review cycles. 

This is possible because we can add an executable script that Heroku will execute after deploys.

**Comment by bdero** [comment]
We've already built HA production and QA environment for Starcellbio which is now running on AWS (starcellbio.mit.edu). Although this could be good for future consideration, I don't think it's really necessary anymore.
