### ISSUE TITLE
'add all' conditions button should behave like a button

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#332]
> The 'Add All' button works great and as expected. I feel like there should be some way to indicate that the button doesn't work when all of the conditions have been added. I was originally envisioning a checkbox, but I'm ok with leaving it as a button. It would be great if you get the pointer cursor when hovering over the button.

button should have an appropriate cursor, and be disabled after used.

**Comment by ald32** [comment]
This seems to be working really well for flow cytometry in Exercise 2. There isn't a "Needs Review" tag on it, but I think it's ok to close this issue. @pdpinch @annagav
