### ISSUE TITLE
Flocytometry 'Set up' page: second line for a sample appears before selecting a condition for the first line

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#334]
The second line within a given sample appears before a condition has been selected for the first line. The second line should only appear after a condition has been selected for the first line.
![screen shot 2015-08-18 at 2 39 35 pm](https://cloud.githubusercontent.com/assets/11359229/9339286/2e874a94-45b7-11e5-916c-76745d0f04dc.png)

**Comment by annagav** [comment]
So this is how it looks for Microscopy:
![screen shot 2016-05-12 at 1 22 48 pm](https://cloud.githubusercontent.com/assets/7574259/15223895/b595f8e0-1844-11e6-8564-744dbed8236b.png)

**Comment by annagav** [comment]
And then when you select a condition it looks like this:
![screen shot 2016-05-12 at 1 23 53 pm](https://cloud.githubusercontent.com/assets/7574259/15223936/e315e8e8-1844-11e6-8d93-c4d91ff7e6b4.png)

**Comment by annagav** [comment]
@laleman @ald32 Would like to change this behavior?

**Comment by ald32** [comment]
@annagav @laleman - I agree with Lourdes initial comment that the second line shouldn't appear at all until the condition is selected, but at the same time, I'm ok with the way it is as it is working and I would like to prioritize the assignment builder.

**Comment by annagav** [comment]
Fixed. 
The second line still appears even before a condition has been selected, but unlike in the original picture the `fixed` radio button does not appear selected.
