### ISSUE TITLE
integration testing

### ISSUE THREAD

**Issue by bdero** [starteam/starcellbio_html#34]
A glance at the tests suggests that there's cleanup needed in this area. All but one test file contains a "hello world":
- https://github.com/starteam/starcellbio_html/blob/41cc4078e328e673d2cd40093bab05ee75e21d03/backend/tests.py
- https://github.com/starteam/starcellbio_html/blob/41cc4078e328e673d2cd40093bab05ee75e21d03/auth/tests.py
- https://github.com/starteam/starcellbio_html/blob/41cc4078e328e673d2cd40093bab05ee75e21d03/instructor/tests.py

And the file that contains tests is in a djangoapp, frontend_tests, which appears to be for integration testing with Selenium.
It contains four tests; here are some notes about them:
- The first test points the Chrome webdriver to `http://localhost:8000/static/index.html` and checks if the response has a `div` with an id `main`.
- This is a baked URL; it's not reverse routed.
- It doesn't appear to launch the server for you.
- This is how it initializes the webdriver: `self.driver = webdriver.Chrome(settings.rel('../../mac/chromedriver'))`
- The second test does the same thing and then checks if some element has a class indicating you're on the homepage.
- The third test does everything else: https://github.com/starteam/starcellbio_html/blob/41cc4078e328e673d2cd40093bab05ee75e21d03/frontend_tests/tests.py#L52-L252
- The last test has a bunch of commented code and executes some JavaScript. It calls the simulateDragSortable plugin on what appears to be some "western blot samples", but doesn't actually assert anything:

``` javascript
script = "$($('.scb_s_western_blot_choose_samples_list_item')[0]).simulateDragSortable({ move: 1 });"
success = self.driver.execute_script(script)
```

There are no unit tests.

**Comment by pdpinch** [comment]
One sample experiment, with one prepartion and one path through each technique: western blot, microscopy and FACS. No login.
