### ISSUE TITLE
Western blotting exp tech - "No marker loaded" text

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#342]
The "No marker loaded" text, which appears when the user does not have a protein marker, should be always visible in the samples window. It should also be repositioned so it has a slight margin surrounding it and is not directly next to the border of the samples window.

**Comment by annagav** [comment]
I think I fixed it. Does this look ok?

![screen shot 2016-10-26 at 2 16 27 pm](https://cloud.githubusercontent.com/assets/7574259/19738674/56b042de-9b86-11e6-9a1e-6fccd6f54b60.png)

**Comment by annagav** [comment]
The marker stays in place when the list scrolls.
