### ISSUE TITLE
Western blotting exp technique - nested scroll bars in the Samples window

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#343]
Two nested scroll bars appear in the samples window when there is a sufficient number of samples to create a scroll bar for the samples list and a scroll bar for all of the items in the window (which includes the gel type, samples list, and the label 'No marker loaded'. This is not very user friendly and should be changed to only have one scroll bar in this window.

**Comment by pdpinch** [comment]
can we get a screenshot?

**Comment by ald32** [comment]
@pdpinch, I got a screenshot only by changing my preferences in system preferences to "always" show scrollbars. It looks a little bit different if you have the setting set to "Automatically based on mouse or trackpad", as the scrollbars are one on top of the other. 
![screen shot 2015-08-25 at 2 33 12 pm](https://cloud.githubusercontent.com/assets/1855065/9475717/74d4eb44-4b36-11e5-9ac2-59813c6918c9.png)

**Comment by annagav** [comment]
This is fixed.

![screen shot 2016-10-26 at 2 16 27 pm](https://cloud.githubusercontent.com/assets/7574259/19738814/cacb0f46-9b86-11e6-89e1-7f98120090fc.png)
