### ISSUE TITLE
Resize the 'Confirm Setup' Dialog window

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#348]
The confirm setup dialog window is too small and is cutting off the text in the window.
![screen shot 2015-08-27 at 11 57 42 am](https://cloud.githubusercontent.com/assets/1855065/9525698/5f2e6788-4cb3-11e5-87f6-b11d576f94bb.png)

**Comment by pdpinch** [comment]
I can't seem to reproduce this. Is this in Chrome? Is it specific to one experiment or another?

**Comment by annagav** [comment]
To reproduce this you have to got to Exercise 3 do the experiment, select 15 samples for WB, click continue. And then, I think, this bug appears.

**Comment by annagav** [comment]
fixed
