### ISSUE TITLE
SUTD #1 Add Samples button doesn't work

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#37]
> I started reviewing SUTD exercise #1 as this is a top priority for this spring. Unfortunately, I can't move past the Experiment setup page as the 'Add Samples' button isn't working. I then logged into the course on which this exercise is based (course code 7.06_Spring_2014) and was able to confirm that I can still perform experiments in this original exercise. Can you look into SUTD exercise #1 for us? If you need more information on this exercise and/or the work that was done to get it ready for SUTD, either Lourdes or I can fill you in.

**Comment by pdpinch** [comment]
@bdero -- when you can -- can we get a deployment of develop (4a6697a876777e7239a0d84dd6dfa4eb47e3f046) so we can test this?

**Comment by bdero** [comment]
This was deployed this morning. Is this issue all set now?

**Comment by pdpinch** [comment]
I'm just waiting for confirmation from Alison or Lourdes.
