### ISSUE TITLE
In Protocols setup, use a combobox for the concentration unit

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#378]
We'd like users to select from a pre-defined list of units, but the user can type in their own unit.

**Comment by annagav** [comment]
Fixed by #384

**Comment by pdpinch** [comment]
please verify on scbdev.odl.mit.edu

**Comment by ald32** [comment]
The dropdown menu works great, but please switch the backslash '\' to a forward slash /.
