### ISSUE TITLE
On protocols screen, add drop-down menu for collection time units

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#388]
same as concentration

**Comment by ald32** [comment]
I'm assuming that we will be limited on space, so I will suggest: sec, min, hr, days.

**Comment by annagav** [comment]
Fixed by #400

**Comment by pdpinch** [comment]
Please verify on scbdev.odl.mit.edu

**Comment by ald32** [comment]
Instead of writing out the terms, can you use the abbreviations?
sec
min
hrs
day
Also, just to confirm, this is relevant for collection time but also start time and duration.

**Comment by annagav** [comment]
This is how it looks now: 
<img width="478" alt="screen shot 2016-10-26 at 2 28 29 pm" src="https://cloud.githubusercontent.com/assets/7574259/19739184/f2f104f2-9b87-11e6-83ce-31ebac8488a8.png">

**Comment by annagav** [comment]
@laleman, @ald32 This a dropdown as well as input box. Is this issue solved?

**Comment by laleman** [comment]
@ald32 --> should we use SI unit abbreviations, in which case it would be:

s
min
h
d

It might be hard to understand what 'd' means. Not sure.

**Comment by annagav** [comment]
@laleman decided to leave it as it is.
