### ISSUE TITLE
in protocol screen, prepopulate units for variables

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#389]
Alison can you comment on this issue with the requirements?

**Comment by ald32** [comment]
In the list below, the 'u' should be the greek letter Mu.
ng/uL
ug/uL
ug/mL
mg/mL
g/L
nM
uM
mm
M

**Comment by pdpinch** [comment]
GitHub supports unicode!

µg/µL
µg/mL
mg/mL
g/L
µM
mm
M

I believe this is the correct unicode character, 'MICRO SIGN' (U+00B5).

**Comment by ald32** [comment]
Great! I updated the list above to add a couple of items with 'nano'
