### ISSUE TITLE
Western Blot Run Gel doesn't work in NSF #3

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#39]

**Comment by pdpinch** [comment]
Confirming this, on:

http://localhost:8080/#view=western_blot_gel&experiment_id=scb_Experiment_1eq9fk8q85l9o&assignment_id=scb_ex3&western_blot_id=scb_WesternBlot_1k0l3lk1kqp0ni&western_blot_gel_id=scb_WesternBlotGel_afdgihg3ggqc

I get repeated JavaScript errors, 

```
TypeError: opt_data.t.primary_anti_body[pabData323] is undefined
```

**Comment by annagav** [comment]
I think this issue does not exist anymore.
