### ISSUE TITLE
Add arrow indicator in left nav to orient user

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#390]
As an instructor, it's hard to know where I am in the Assignment Builder. An indicator in the left nav pointing to the current screen would be helpful.

**Comment by ald32** [comment]
This should look just like it does within the assignments tab of the main SCB program.
![screen shot 2015-10-20 at 3 33 41 pm](https://cloud.githubusercontent.com/assets/1855065/10618813/f5d62af2-773f-11e5-95ac-5d5040385d17.png)
