### ISSUE TITLE
Western Blot: band intensity page, generating samples

### ISSUE THREAD

**Issue by annagav** [starteam/starcellbio_html#424]
Things we discussed with Alison:
1) Create a band for each entered size on the previous page, unless the instructor left it empty. 
2) (in the band sizes page) The instructor can enter any non negative numbers (including decimal numbers), separating them by a comma. Negative numbers do not generate a band.
3) The lysate types should appear in the table as : 'WCL', 'Nuc', 'Cyto'.
4) Antibody heading should not be numbered.

**Comment by pdpinch** [comment]
done?
