### ISSUE TITLE
Western Blot: Intensity view: update text to explain band size

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#440]
@laleman will provide the updated text

Change the notes to a list also.

**Comment by annagav** [comment]
@laleman This is how it looks like right now:
<img width="674" alt="screen shot 2016-10-26 at 4 26 38 pm" src="https://cloud.githubusercontent.com/assets/7574259/19743761/900cb65e-9b98-11e6-827f-4c46ea9f5e60.png">

**Comment by annagav** [comment]
@laleman more text is needed, right?

**Comment by laleman** [comment]
Change to the following:
Define the relative band intensity for each of the proteins detected in your samples and lysate type  combinations.
