### ISSUE TITLE
On protocols page, conditions are not listed in the same order for all samples

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#444]
On the protocols page, I think that all of the correct combinations are showing up, but the different options in the concentration column are appearing in different order for different samples. Something must be happening when the concentration and temperature columns are being sorted.
<img width="564" alt="screen shot 2015-11-30 at 11 35 30 am" src="https://cloud.githubusercontent.com/assets/1855065/11477604/b5c42f5e-9756-11e5-821a-5e0ab5a617c4.png">

**Comment by ald32** [comment]
Need to sort by concentration, start time, and duration, in addition to strain, treatment, collection time, and temperature. Columns should be sorted in a left -> right order.

**Comment by annagav** [comment]
This was fixed
