### ISSUE TITLE
Western blot band intensity page: samples should appear in the same order as the protocols page

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#450]
The samples seem to be ordered differently on the band intensity page than on the protocols page.

**Comment by ald32** [comment]
The samples are being correctly sorted in the name column, but they are not being sorted by size. The samples should be sorted by sample name, then size (and all of the sizes should always be in the same order).

**Comment by annagav** [comment]
@ald32, I think this has been fixed.

**Comment by ald32** [comment]
Me too. Closing it now.
