### ISSUE TITLE
StarCellBio: update basic microscopy animation YouTube link

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#453]
I just had to upload a newer version of one of the animations. Can you please update the YouTube link for the basic microscopy video in the 'In the Lab' feature box?
The new link is: https://youtu.be/OPv84Tdgj-Y

**Comment by annagav** [comment]
@ald32, only one video. The other two seem to be only few seconds long.

**Comment by annagav** [comment]
Ok, I found them in issue #382

**Comment by ald32** [comment]
Were you able to find all the animations? They should all be at least a couple of minutes in length. Do you need me to check the links @annagav ?
