### ISSUE TITLE
Assignment builder preview: Update Add Samples dialog to new format

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#462]
Format the Add samples dialog window so that it matches the current format in SCB. This means that there should be 'Select all' and 'Clear all' buttons. Also the entire sample protocol name should appear including the strain, treatment, and all other relevant conditions.

**Comment by annagav** [comment]
This is on scbdev. @ald32 , please make sure it looks (and works) as aspected.

**Comment by ald32** [comment]
This looks great!
