### ISSUE TITLE
Instructor Account: change message at top when user sets up Instructor Account

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#476]
The message at the top of the "Create Instructor Account' should be changed to reflect that the user is not trying to set up a student account. The message should read:

In the instructor account, instructors set up and customize their own StarCellBio assignments and experiments. The email address for the instructor account must be different from those used to set up other StarCellBio accounts. To set up an instructor account, enter your email and password below and then click Create Account. 

[Please note that the 'Create Account' text in the message above should be in bold and in the same green color as the button.]

**Comment by ald32** [comment]
I don't see this change. Has it been made yet?

**Comment by pdpinch** [comment]
I don' t think so. I believe it's waiting on #533
