### ISSUE TITLE
Dashboard: when publishing an assignment, show a confirmation message

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#481]
As an instructor, I need to know that when I publish an assignment, I will no longer be able to edit it.

**Comment by ald32** [comment]
When the instructor clicks the 'Publish' link in the actions table, a dialog window should come up that reads:
Please confirm that you would like to publish your assignment. Once an assignment is published, the assignment will no longer be able to be edited in the Assignment Builder. Users will be able to access the assignment using the provided course code on the StarCellBio website. Would you like to continue?

Yes/No are the options.
