### ISSUE TITLE
Resolve merge conflicts between develop and master...

### ISSUE THREAD

**Issue by bdero** [starteam/starcellbio_html#49]

**Comment by pdpinch** [comment]
@bdero how scared should I be of this? Is it possible to estimate how long this will take?

**Comment by pdpinch** [comment]
Now that we found out that the prod server isn't running on master, I don't think we need to do this any more. 

I do wonder what we should do with the master branch though...

**Comment by carsongee** [comment]
I think we should just replace it, i.e.

```
git push origin :master
git push origin develop:master
```

That might be a little risky though
