### ISSUE TITLE
Exercise definitions are shoved into the database for each assignment to a user

### ISSUE THREAD

**Issue by bdero** [starteam/starcellbio_html#50]
They're pretty large.

Most likely, this makes it impossible for students to see any changes to exercises once they've been assigned.

**Comment by pdpinch** [comment]
According to @ald32 , not allowing changes was a design feature:

> In terms of the instructor account, we thought of this previously but decided that an instructor cannot make edits to an already published assignment. We thought this would create complications if a student has already started the assignment and we also thought that the potential problems would depend upon the type of changes the instructor would like to make. But we can talk about this again when we are ready to tackle the instructor account and see what you think about this. 

I think we still want to look at the mingling of problem content state and student state, but we should keep this design goal in mind.
