### ISSUE TITLE
Publish assignment so student can view

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#501]
- [x] compile assignment, similar to preview
- [x] save resulting json to student table

**Comment by annagav** [comment]
#370 is a duplicate.

**Comment by ald32** [comment]
I can log in with the course code that I just made and see the assignment! Amazing! I did notice a small thing (that is also on the list to change for the preview mode): the instructions on the experiment setup page are no longer appearing. Everything else seems to be working beautifully!! - By the way, this isn't a major problem and I'm happy to move forward.
