### ISSUE TITLE
Prevent instructors from previewing their assignment before it is completely defined

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#506]
An instructor should not be able to preview their assignment if they try to 'Preview' their assignment before the experiment setup and one experimental technique have been defined. A dialog window should appear that says:
You must define your experimental setup and the variables for at least one experimental technique before you can preview the assignment.
'OK'

**Comment by annagav** [comment]
@ald32, What should the error message say when the assignment is not ready for preview?

**Comment by annagav** [comment]
Oops, sorry. Now I see it!

**Comment by ald32** [comment]
Ok! :)

**Comment by ald32** [comment]
This seems to be working ok. If I'm on experimental setup, then I can't preview the assignment. I get an error in the browser window. I do think that this should be formatted so it looks nicer. Once I select western blotting as my experimental technique, I can preview the assignment, but the antibody dropdown menus are blank. I actually think this is ok, although hopefully not confusing for the instructor. In the future, we can either prevent them from seeing the assignment all together or allow them to see only what has been created so far.
