### ISSUE TITLE
Instructor account - make contact link work

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#511]
The contact link should work so that an instructor can easily contact us from within the instructor account. 

Currently, the user guide link doesn't work (and isn't relevant for an instructor as there isn't any information in it about the instructor account. Also the videos link is missing, but again isn't too relevant as there aren't any videos yet on using the instructor account.

**Comment by pdpinch** [comment]
Where does the contact link appear?

**Comment by ald32** [comment]
the contact link is at the top of every page, near the sign in/ sign out link.

**Comment by ald32** [comment]
This is working on the dev site.
