### ISSUE TITLE
Contact Link isn't working

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#536]
We just got an email from a StarCellBio user (who managed to track down Lourdes) that the 'contact' link on the StarCellBio website isn't working. I just tried it myself and got an error too. However, it does seem to be working on the ODL development site.

**Comment by pdpinch** [comment]
Hmm. I thought we had fixed this recently. 

It's throwing a 500, but the page is updated faster than I can capture the error.

**Comment by ald32** [comment]
Maybe it was fixed recently which is why it's working on the dev site but not the main SCB site? I just wanted to let you know that we were contacted with that issue.

**Comment by pdpinch** [comment]
@blarghmatey would you mind looking into this, if things are slow?

FYI @bdero

**Comment by blarghmatey** [comment]
@pdpinch Taking a look now

**Comment by pdpinch** [comment]
I believe this is fixed.
