### ISSUE TITLE
Load test with JMeter or an equivalent tool

### ISSUE THREAD

**Issue by bdero** [starteam/starcellbio_html#55]
Since we're expecting a large amount of traffic (over 300 students) soon.

**Comment by pdpinch** [comment]
Draft test plan at https://github.mit.edu/mitx-devops/jmeter/blob/pdpinch/scb-test-plan/scb.jmx

**Comment by pdpinch** [comment]
We will revisit this as soon as we are able to deploy a server to AWS.
