### ISSUE TITLE
SUTD Exercise #1 - microscopy images are not displaying correctly

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#56]
The microscopy images are not appearing confined to the microscopy lens. Instead they are appearing as a square over the microscopy lens.

https://scbdev.mit.edu/#view=microscopy&assignment_id=sutd_intro_biology&experiment_id=scb_Experiment_1a8p5d2913oam&microscopy_id=scb_Microscopy_id42f91k46g13

**Comment by pdpinch** [comment]
@ald32 @laleman please review on scbdev.mit.edu

**Comment by ald32** [comment]
The images are displaying correctly for me now.

**Comment by laleman** [comment]
They are displaying for me too. Yeah!!!! (doing cartwheels).

**Comment by pdpinch** [comment]
:smile:
