### ISSUE TITLE
SUTD Exercise #2 - Flow cytometry results for siRNA #1 and siRNA #2 are wrong.

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#567]
siRNA #1 and siRNA #2 should yield a histogram centered around value 100 not 50, which is what it is currently showing. See "StarCellBio --> SUTD --> Assignment 2 --> Coding Ver4" for specifics. 
![screen shot 2016-01-27 at 12 13 26 pm](https://cloud.githubusercontent.com/assets/11359229/12621635/6cbea2dc-c4ef-11e5-997e-ee60a1d8fd22.png)

**Comment by laleman** [comment]
Hi Anna. Where are we with this particular bug/fix?

**Comment by annagav** [comment]
@laleman, The fix is waiting for review now. Is there a deadline for this fix?

**Comment by laleman** [comment]
Anna, do I have to create a new account? Is my account on this site wiped out? The account I had just created two weeks ago was not working.

**Comment by annagav** [comment]
Sorry, I meant that it is ready for code review. I will let you know when you can take a look at it. 
You will have to create a new student account to see the change.

**Comment by laleman** [comment]
OK, got it. Thank you!

**Comment by laleman** [comment]
Anna, I thought this bug had gotten fixed and it does not seem that it ever did. This is for the SUTD exercise that the students are currently doing.
