### ISSUE TITLE
AB: FACS Sample Prep page

### ISSUE THREAD

**Issue by annagav** [starteam/starcellbio_html#569]
Define combinations of cell treatments, analysis and conditions. Design document: Problem Set Builder/User Interface Design Documents - Jamie Waters/SCB_ProblemSetBuilder_09_FlowCyt.pdf

**Comment by pdpinch** [comment]
Is this issue just this screen?

![image](https://cloud.githubusercontent.com/assets/430126/12724047/139fa306-c8da-11e5-90e7-78c77be22196.png)

https://www.dropbox.com/s/5dy257x6e4kc5sb/SCB_ProblemSetBuilder_09_FlowCyt.pdf?dl=0

**Comment by annagav** [comment]
That looks correct.
