### ISSUE TITLE
Lab report button should not be functional

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#57]
When users click on the lab report button, an error message should appear that says: 'Under Construction'. Our error messages are usually formatted with a green bar at the top - as seen in the attached image.

This applies to all exercises within StarCellBio, but is especially relevant for SUTD Exercise #1 that is being deployed soon.
![screen shot 2015-03-04 at 2 27 33 pm](https://cloud.githubusercontent.com/assets/1855065/6491366/b80c3934-c27a-11e4-96c5-9a9ba276081d.png)

**Comment by pdpinch** [comment]
@laleman Is there a reason for responding "under construction" instead of removing the button altogether?

**Comment by laleman** [comment]
I think we thought it would be a quicker fix and would not mess up with UI look and feel too much but I if you think neither is a big deal, I am up for trying to remove it for now.

**Comment by pdpinch** [comment]
Anna's already written the code to make it non-functional. I'd like to just "grey" it out as well.

**Comment by laleman** [comment]
I no longer see the button and the UI looks great.
