### ISSUE TITLE
Discovery: graph sketching tool recommended by the Math team

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#571]
> We're not using a specific library at the moment, but JSXGraph (http://jsxgraph.uni-bayreuth.de/wp/) sounds like it would be a good fit for your application (or possibly D3.js, though I suspect JSXGraph would be easier). The library includes the ability to plot functions/axes and make items draggable out of the box, so you could probably get something working with it without too much code.
> 
> The JSXGraph site contains lots of examples to help you get up to speed, and Davidson has also used JSXGraph a lot to develop interactive graphical tools... see, e.g., http://dnextinteractives.s3.amazonaws.com/WWW/graphing.html (a relevant example is "Curve Shifting (drag)"). The DavidsonNext GitHub has all their source code if you want to see how they do things: https://github.com/DavidsonNext/ (make sure to check their license terms if you end up copying anything verbatim though).

**Comment by pdpinch** [comment]
@annagav have you decided to go ahead with JSXGraph, or something else?

**Comment by annagav** [comment]
Using html canvas and paper js.
