### ISSUE TITLE
AB: FACS Analyze page - select histogram form

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#572]
from https://www.dropbox.com/s/5dy257x6e4kc5sb/SCB_ProblemSetBuilder_09_FlowCyt.pdf?dl=0: 

Just this form: 

![image](https://cloud.githubusercontent.com/assets/430126/12724729/44bf2562-c8dd-11e5-9859-72681bd9b91d.png)

**Comment by annagav** [comment]
I would separate this into to different issues.

**Comment by pdpinch** [comment]
Ok. Done.
