### ISSUE TITLE
SUTD Exercise #1 - Disable the left & right arrows on the assignment page

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#58]
Disable the left and right arrows on the assignment page. This applies to the arrows at both the top and bottom of the page so students don't think there is more to the assignment (online) on other pages.

https://scbdev.mit.edu/#view=assignments&assignment_id=sutd_intro_biology

**Comment by pdpinch** [comment]
Generically, if there's one (or less!) tabs on the assignment page, the arrows should not appear.

**Comment by ald32** [comment]
That would be great if the arrows don't appear when there is only one tab on the assignment page. I do see them in both of the SUTD Exercises. 
![screen shot 2015-03-09 at 1 38 59 pm](https://cloud.githubusercontent.com/assets/1855065/6560596/bfc9a9dc-c661-11e4-9006-4a3e819412ef.png)

**Comment by pdpinch** [comment]
Both assignments should display the correct text now, and the arrow buttons should be appropriately disabled/removed. Please test @laleman or @ald32

**Comment by ald32** [comment]
I see the arrows at the top of the page, but they are disabled, and the tabs are no longer appearing at the bottom of the page. In the assignment window itself, it just says "Please refer to your instructor for detailed instructions." now. So I think everything looks right!

**Comment by ald32** [comment]
I forgot to mention that the tab heading still says "Goal & Introduction". Can this be changed to "Assignment Text"? 
Also, in the long term, can the arrows on either side of the tab not appear if/when there is only one tab?

**Comment by pdpinch** [comment]
I'm closing this issue and opening #96 and #97 to address the feedback.
