### ISSUE TITLE
Add instructions on how to download soyutils library and remove it from the repo

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#583]
soyutils is used in the build process, but doesn't need to be part of the web app. 

We should encourage users to download and run it themselves, so we don't have to worry about licensing.

**Comment by pdpinch** [comment]
Does using bower or an npm package address this?

**Comment by pdpinch** [comment]
No instructions necessary. I added this to the npm install and made some adjustments to ansible and travis to move the location of npm modules. I'll have to run these changes by @starteam/devops

**Comment by jmclaus** [comment]
@pdpinch @annagav  We should close this, related [PR](https://github.com/starteam/starcellbio_html/pull/769) has been merged.

**Comment by pdpinch** [comment]
Thanks @jmclaus
