### ISSUE TITLE
add instructions on how to download jqdialog library and remove it from the repo

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#584]
TLO (Technology Licensing Office) finds the jqdialog library's license is incompatible with our GPL2 library. It should be removed from the repository and replaced with instructions on how to download it.

**Comment by pdpinch** [comment]
Simliar to #583

**Comment by jmclaus** [comment]
@pdpinch @annagav That's a tricky one as JQDialog isn't an npm module, I've only found a copy of it on GitHub at:

https://github.com/knadh/jqdialog

But we could use a post install  npm script to download it. For example, we could use the cli version of the very popular `download` node package:

https://www.npmjs.com/package/download
https://www.npmjs.com/package/download-cli

by adding this entry to our `html_all/package.json` file:
`"download-cli": "^1.0.5"`

Then add a post install script to the same `package.json` file:
```
"scripts": {
    "postinstall": "download --out ./js https://raw.githubusercontent.com/knadh/jqdialog/master/jqdialog.js"
}

```

Should I create a branch off of develop and open a PR so you can test it out?

**Comment by jmclaus** [comment]
@pdpinch @annagav Easier to just download the file with Ansible. PR is [here](https://github.com/starteam/starcellbio_html/pull/769).

**Comment by jmclaus** [comment]
@pdpinch @annagav  We should close this, related [PR](https://github.com/starteam/starcellbio_html/pull/769) has been merged.

**Comment by pdpinch** [comment]
Thank you @jmclaus
