### ISSUE TITLE
discovery: can we use our new standard release process

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#588]
Find out how much of our new standard script can work. Document the release process and any variances from the standard.

**Comment by pwilkins** [comment]
The release script repository is here: https://github.com/mitodl/release-script

**Comment by pdpinch** [comment]
@justinabrahms @pwilkins @annagav @blarghmatey does anyone have an opinion on this?

I don't think we're going to do much cellbio work next sprint (ending 3/11). If this isn't resolved, can it wait until the end of March?

**Comment by justinabrahms** [comment]
There shouldn't be anything in scb that would keep us from using the
release script.

On Friday, February 26, 2016, Peter Pinch notifications@github.com wrote:

> @justinabrahms https://github.com/justinabrahms @pwilkins
> https://github.com/pwilkins @annagav https://github.com/annagav
> @blarghmatey https://github.com/blarghmatey does anyone have an opinion
> on this?
> 
> I don't think we're going to do much cellbio work next sprint (ending
> 3/11). If this isn't resolved, can it wait until the end of March?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/starteam/starcellbio_html/issues/588#issuecomment-189318199
> .

## 

Sent via mobile phone.
