### ISSUE TITLE
Videos link should open in a new tab

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#59]
The videos link - both at the top of every page and within the user guide - should open the videos YouTube website within a new tab.

**Comment by pdpinch** [comment]
@ald32 what about the "in the lab" video player? Should those videos open in a new tab as well?

**Comment by laleman** [comment]
Yes that would be nice. Thank you.

**Comment by pdpinch** [comment]
This will also close #75 and #24

**Comment by annagav** [comment]
Fixed by #103.

**Comment by pdpinch** [comment]
#103 fixed a different issue.

**Comment by ald32** [comment]
Right, as we mentioned in last week's SCB meeting, we would like the Videos icon at the top of every page (and within the User Guide) to open a new tab. The 'In the Lab' videos are playing appropriately now.
