### ISSUE TITLE
FACS: add default value for condition name

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#602]
As an instructor, I may not know what "condition name" means. A default value would help me understand the meaning of this field. Ideally, the default value would change when I change the analysis to suggest a potentially relevant name. 

The term "Condition" may not be intuitive to instructors.

**Comment by ald32** [comment]
Default name for dye/stain would be 'propidium iodide'. Default name for antibody labeling would be 'Histone H3 antibody'.
