### ISSUE TITLE
AB FACS: preview option for graphs

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#605]
As an instructor, I want to be able to see what my graphs will look like for students, and I want them to look realistic. 

We will need a function to add noise to the hand-drawn graphs. 

Ideally, we would apply the function as soon as the drawing is finished. It's okay if the noise is random and slightly different every time. 
- [ ] We need to add a note to the instructor that (sample) noise is added to the graph, to make it look more realistic.

**Comment by ald32** [comment]
Yes and we discussed that the instructor would be able to preview what the graphs will look like when the thumbnails are shown on the 'Analyze' page. Or once the instructor draws the curve and releases the mouse, then the noise is added in the small window before the graph is even saved or discarded.

**Comment by pdpinch** [comment]
The noise may not be visible in the thumbnail, because of the size.
