### ISSUE TITLE
Integration tests for creating student accounts

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#606]
As a devops, I'd like a test that I can run to confirm that student accounts can be created successfully on a deployment.

For some time in production, account creation was failing with a 500 error. We're still not entirely sure what the cause was, but we'd like to have better tooling to detect it in the future.

To create a student account, we will need a course code.

**Comment by justinabrahms** [comment]
Can you send me the 500 error? It would be helpful to see which API call was failing to write the test-driver against.

**Comment by pdpinch** [comment]
Frustratingly, I cannot. We were having problems with logging at the time the 500s were being generated and they apparently weren't captured. 

I suspect it had to do with the e-mail configuration and/or code though. It appeared as though accounts were getting created despite the 500 error. And this error was happening when we were also getting 500s from the contact form. 

@blarghmatey did you ever find a stack trace?

**Comment by justinabrahms** [comment]
Alternatively, what's the ideal invocation of it? Bash script + curl? Selenium thing you run in your own browser? Something else?

It seems like a big question on the servers is monitoring. I would recommend getting health checks setup in the app, which can test that the mail server is running (or whatever else), rather than adding lots of manual QA steps after the deploy.

**Comment by blarghmatey** [comment]
@pdpinch I didn't ever find a stack trace for the account creation error.

**Comment by pdpinch** [comment]
I was assuming Selenium similar to the other tests. The end goal would be to have something that travis can run. 

For monitoring, do you think we can use the server status app?

**Comment by justinabrahms** [comment]
We can use server status, but only if we know what it is we should be
monitoring.

**Comment by justinabrahms** [comment]
Is there a course ID which always exists on production? We need this to create the user.

**Comment by pdpinch** [comment]
The course we care the most about is SUTD_biology (not sure about case)

@annagav may know if there's another one more appropriate for testing.
