### ISSUE TITLE
The order of included scripts when running build.py is not deterministic

### ISSUE THREAD

**Issue by bdero** [starteam/starcellbio_html#62]
This causes the need for manual reordering during deployment since the order of the included scripts is super important.

https://github.com/starteam/starcellbio_html/blob/639381461d4017a0648acc8055e714a36f93123c/html_app/build.py#L94-L98

**Comment by carsongee** [comment]
Any objections to just making all the JS dependencies a flat hard coded list, or do we want to keep the dynamic asset discovery and just figure out what dep is breaking things?

**Comment by pdpinch** [comment]
I haven't used the dynamic asset discovery yet, so I'm fine with a hard-coded list. But we should also check with @annagav

**Comment by carsongee** [comment]
It is currently ~112 files, so a long list, but I don't know how often it is changed

**Comment by annagav** [comment]
No objections
