### ISSUE TITLE
FACS sample prep: Implement cell treatment option 'Live' and 'Fixed'

### ISSUE THREAD

**Issue by annagav** [starteam/starcellbio_html#631]
As a student, I should be able to see two options for 'Cell Treatment' during 'Sample Prep' step.

When cell treatment is selected a placeholder appears for other options.

**Comment by annagav** [comment]
@ald32, I remember you asked to have two rows for a sample with Live and Fixed cell treatment in the analyze view, is that right?

**Comment by ald32** [comment]
@annagav, 
In response to your first comment, the student will only see two options (Fixed and Live) if that is an option that the instructor provides. There are many scenarios where only one cell treatment will be available.
For the second comment, this is correct if a student has both fixed and live available to them and they select both. This would mean that if both fixed and live are available on the set up page, and the student first selects fixed, then populates the analysis and conditions columns, that another sub-row would appear in case the student wants to select another fixed or live treatment, right? Have we discussed this previously? This could be much more complicated than we have currently observed in flow cytometry up to now.

**Comment by annagav** [comment]
Yes we have discussed this before. We talked about how to display the  cell treatment in the 'analyze' view, and we thought we have 2 options: either add in tabs (just like the analysis and condition), or add it as another row in the samples list on the left.

**Comment by ald32** [comment]
Let's make it another row in the samples list - but it will be really important that the user can actually see "fixed' and 'live' in the sample name.
