### ISSUE TITLE
Bug in flow cytometry cell treatment options

### ISSUE THREAD

**Issue by noisecapella** [starteam/starcellbio_html#639]
![screenshot from 2016-06-15 12-03-35](https://cloud.githubusercontent.com/assets/863262/16087530/44847ed4-32f1-11e6-8682-cb1a3dca5e39.png)

**Comment by annagav** [comment]
The bug occurs in the 'sample prep' step in FACS, when trying to select the third defined set of variables (defined above) for the experiment.
