### ISSUE TITLE
What happens if instructor does not assign a histogram to a sample?

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#643]

**Comment by ald32** [comment]
The instructor has to assign a histogram to a sample in order to proceed. So if a histogram is not assigned, then a warning will appear that asks the instructor to go back and assign one.

**Comment by annagav** [comment]
In this case it does not let you 'Preview or Publish' the assignment. When trying to preview, need a better message when assignment is not finished.

**Comment by annagav** [comment]
Change the error message to: 
'Your assignment cannot be previewed. Make sure you have:
* defined the experimental setup and variables for at LEAST ONE experimental technique,
* assigned histograms to all samples in flow cytometry if using this technique'

Add instructions to each technique to indicate the rules for completeness for Preview.

**Comment by pdpinch** [comment]
closed via #751
