### ISSUE TITLE
Add instructions for the histogram sketching tool

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#644]
As an instructor it may not be obvious how to use the sketching tool. I'd like some instructions.

**Comment by ald32** [comment]
@pdpinch, @laleman , @annagav - How about: To draw a histogram, click and drag your cursor within the graph to make the desired shape.

**Comment by annagav** [comment]
@laleman modified to:
To draw a histogram, click and drag your cursor within the graph.
