### ISSUE TITLE
Some registration field validation errors don't look like errors

### ISSUE THREAD

**Issue by bdero** [starteam/starcellbio_html#65]
When you input a password less than 6 characters, this is what happens:
![Screenshot](http://i.imgur.com/FQvKoqT.png)

The email validation shows up as red along with an asterisk.

**Comment by pdpinch** [comment]
FWIW, this looks better on starcellbio.mit.edu -- perhaps there is some missing, or conflicted, css.

**Comment by annagav** [comment]
<img width="431" alt="screen shot 2016-10-14 at 3 19 39 pm" src="https://cloud.githubusercontent.com/assets/7574259/19399781/287ee0c8-9221-11e6-8492-113116d74be2.png">
