### ISSUE TITLE
AB Microscopy: Upload images to S3 in production.

### ISSUE THREAD

**Issue by annagav** [starteam/starcellbio_html#658]
DevOps needs to:
- [ ] create s3 bucket
- [ ] update configuration for dev server and live server (?)

**Comment by pdpinch** [comment]
@starteam/devops can you guys give us some guidance on what needs to be done with this?

**Comment by ald32** [comment]
To clarify, am I part of the star team?

**Comment by blarghmatey** [comment]
I believe this is complete. I am happy to reopen it if that is not the case.
