### ISSUE TITLE
AB FACS: Left justify the instructions in sample prep

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#663]
Sample prep page:
- Left justify the instructions

**Comment by annagav** [comment]
Not sure what to fix here.
![screen shot 2016-07-28 at 2 09 44 pm](https://cloud.githubusercontent.com/assets/7574259/17223973/eeded1a2-54cc-11e6-8c47-6bda7483b68b.png)

**Comment by annagav** [comment]
It was decided to make just this change: add space in 'Flow Cytometry'.
