### ISSUE TITLE
AB FACS: in analyze form, controls shouldn't be on the same line as the heading

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#666]
i.e. "edit" and "copy to another sample" shouldn't be on the same line as "Live, Anitoby-labeling, Histone H3 Antibody"

**Comment by annagav** [comment]
@ald32 , @laleman In the design documents it looks like they are on the same line. Do we want to change this?
<img width="690" alt="screen shot 2016-07-28 at 2 13 32 pm" src="https://cloud.githubusercontent.com/assets/7574259/17224127/98fed9ca-54cd-11e6-8eb7-87fba405227f.png">
