### ISSUE TITLE
AB Microscopy: instructions for image upload

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#670]
microscropy images must be a minimum pixel size in order to display properly in the viewer. We need to tell users the requirements.

**Comment by ald32** [comment]
@pdpinch @annagav 
In the design document (https://www.dropbox.com/s/g09wtvggn9ry1ck/SCB_ProblemSetBuilder_09_Microscopy.pdf?dl=0) we included instructions that said: 
Note: We recommend that images are at least 500x500 pixels for optimal viewing in StarCellBio.

We can add this line, but update it with relevant information for StarCellBio as appropriate. Do you know how big the images need to be?

**Comment by annagav** [comment]
For SUTD#2 assignment we had images 400x400, for NSF#3 all images are 500x500px.

**Comment by ald32** [comment]
@annagav , were the 400x400 images ok to use or a little smaller than what we would ideally recommend?

**Comment by annagav** [comment]
I am not sure how to evaluate this, since the images appear at random places within the microscope, and when you move the image around you can see all the edges of the image independently of the size.

**Comment by ald32** [comment]
I think it needs to be big enough so that when the image is centered in the viewfinder, the viewfinder is completely filled with the image. You shouldn't see the edges of the image until you move the image around.
