### ISSUE TITLE
AB Microscopy: Allow instructor to upload images for different filters, when using Fluorescent analysis

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#697]
When an instructor chooses antibody-labeling for analysis and then progresses to the upload form, she needs to be able to upload an image for each sample, with each of four filters: red, blue, green and all filters. 

As elsewhere in microscopy, not all images are required.

**Comment by pdpinch** [comment]
@annagav I think this applies to more analysis options than just Antibody-labeling?

**Comment by pdpinch** [comment]
We're not sure what is the best way to do this. We can present the user with a image button for each folder, for each sample, that may be overwhelming. We can let the instructor choose which filters apply before getting to the upload form. Or we could allow the instructor to hide unused filter/sample combinations.

**Comment by annagav** [comment]
Analysis types:
dye/stain (brightfield) - H&E (or Hematoxylin & Eosin if you have enough room)
dye/stain (fluorescence) - DAPI                      <--- with filters
antibody labeling IF - histone H3 antibody    <--- with filters
antibody labeling IHC - histone H3 antibody
fluorescence -> GFP-tagged protein              <--- with filters
brightfield -> (N/A)
