### ISSUE TITLE
SUTD Exercise #2 - Western Blotting: antibody anti-pgk1 does not yield bands

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#70]
When primary antibody "rabbit anti-pgk1" is paired with secondary antibody "goat anti-rabbit" it should result in a band of size 45 that is of the same intensity across all of the samples. No bands currently show using these conditions.
![screen shot 2015-03-08 at 9 22 46 pm](https://cloud.githubusercontent.com/assets/11359229/6548742/50ffb236-c5d9-11e4-8a63-c1cb472573de.png)

**Comment by annagav** [comment]
This was fixed by #83

**Comment by pdpinch** [comment]
@ald32 @laleman please review on scbdev.mit.edu

**Comment by ald32** [comment]
The proper bands appear for me now.

**Comment by pdpinch** [comment]
Thanks!
