### ISSUE TITLE
SUTD Exercise #2 - Flow Cytometry: "Conditions" should be left blank for this particular exercise

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#72]
An example of how it should look like can be found in 2014 7.06 Assignment #2
![screen shot 2015-03-08 at 9 28 59 pm](https://cloud.githubusercontent.com/assets/11359229/6548768/531fc758-c5da-11e4-9377-19ffd2d8c7b9.png)

**Comment by ald32** [comment]
I'm surprised that we had an empty conditions column in the assignment last spring. I think it would be more clear for the students if we delete this column entirely.

**Comment by pdpinch** [comment]
Anna is still working on a way to hide the column. For now, the column will at least be empty (similar to 7.06 #2. 

I will close this issue when it is confirmed empty, and open a new (low priority) one for removing the column.

**Comment by ald32** [comment]
The column is appearing empty to me - no conditions are appearing for each row of the table, but I do see the "Conditions" heading.

**Comment by pdpinch** [comment]
Closing this one and opening a new issue to track removing the empty column, #94
