### ISSUE TITLE
In Microscopy Analyze, change cursor on hovering over the "add images" buttons

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#720]

**Comment by annagav** [comment]
My cursor changes on hovering over `add image(s)` button. Not sure if I am looking at the wrong button.
![screen shot 2016-09-16 at 3 36 55 pm](https://cloud.githubusercontent.com/assets/7574259/18598854/1d1781b8-7c23-11e6-9b61-65fb03aa1f1d.png)
