### ISSUE TITLE
SUTD Exercise #2 - Flow Cytometry: clicking and dragging for drawing gates not working properly

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#73]
The gates appear in a location that is slightly off from where you actually click and drag to demarcate the area they occupy (for both the single and the bisector gate tools)

**Comment by pdpinch** [comment]
@laleman Can you point us to a working example of this, perhaps on starcellbio.mit.edu ?

**Comment by laleman** [comment]
I was trying to think of a way to document this last night but realized that it is not possible since as soon as you lift the cursor the gate is gets drawn making it impossible to take a screen shot as the same time as I am trying to demarcate the gate. 

Let say you have a peak that you want to draw the gate so that the left boundary of the gate is where the peak begins and the right boundary is where the peak ends. The gate when drawn should then begin on the left boundary and should end at the right boundary, exactly where you placed them. What it is shown in the figure provided where the gate was drawn in this particular example. The red vertical lines correspond to where the cursor was placed to demarcate the left and right boundaries. The black gate is where the gate should be drawn (appropriately drawn in the production site). The horizontal blue line is what instead we see in the StarCellBio dev site. 
![screen shot 2015-03-09 at 10 46 19 am](https://cloud.githubusercontent.com/assets/11359229/6557391/059fd790-c64b-11e4-9bbc-a2fd198871cc.png)

**Comment by pdpinch** [comment]
Using the javascript debugger in Chrome, I am wondering about this line: https://github.com/starteam/starcellbio_html/blob/develop/html_app/ui/FacsView.js#L789

@annagav

**Comment by pdpinch** [comment]
Narrowing it down a bit more, 

on prod, plot.pointOffset({x: 0, y: 0}).left returns 22
on dev, plot.pointOffset({x: 0, y: 0}).left returns 2

I think we need to look into how the plot object is configured and whether that's changed.

**Comment by pdpinch** [comment]
@laleman @ald32 -- Anna just fixed this issue and it's up on scbdev. 

Please confirm that the facs analysis tools are working as expected when you click and drag on the graphs.

**Comment by annagav** [comment]
This fix does not include the labeling of the gates on graphs through "apply all" button.

**Comment by laleman** [comment]
It is resolved for me.

**Comment by ald32** [comment]
It works for me too
