### ISSUE TITLE
Assignment builder microscopy: Remember instructor's position on page

### ISSUE THREAD

**Issue by ald32** [starteam/starcellbio_html#733]
Remember the instructor's position on the microscopy analyze page. This will help when instructors are uploading lots of images for many samples.

**Comment by pdpinch** [comment]
I found that sometimes the scroll values wasn't an integer, so you should convert it to an integer.

**Comment by pdpinch** [comment]
@laleman is this still necessary? 

We have an old PR that sort of fixed it, but I doubt it works with all the other changes.

**Comment by ald32** [comment]
@pdpinch @laleman - I agree that this is probably no longer relevant as there have been quite a lot of changes to the microscopy user interface in the assignment builder.
