### ISSUE TITLE
Flow Cytometry: Bisector gate "Apply All" button does not apply labels to all graphs

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#74]
When you apply the bisector gate to all of the samples only the original sample used to create the gates has the "a" and "b" labels on top of the gates

In the example provided, the bisector gate was used for the "Control siRNA" sample. After the button "Apply All" has been checked, all of the other samples should have the same gates applied to them with the same labels. I am providing an example of siRNA #1 sample so that you can see that the gates are missing the "a" and "b" labels from gates. 
![screen shot 2015-03-08 at 9 41 22 pm](https://cloud.githubusercontent.com/assets/11359229/6548820/2015b276-c5dc-11e4-9184-8b4faba98844.png)
![screen shot 2015-03-08 at 9 41 30 pm](https://cloud.githubusercontent.com/assets/11359229/6548821/24762ca6-c5dc-11e4-9da8-4d2fafb1b105.png)

**Comment by pdpinch** [comment]
@laleman is this working on starcellbio.mit.edu ?

**Comment by laleman** [comment]
Also not working in starcellbio.mit.edu
