### ISSUE TITLE
SUTD Exercise #2 - Video thumbnail does not resize properly after playing it in Full Screen

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#75]
This is within the "In the Lab" small screen which appears in several locations throughout the tool. Example here is taking from Western Blotting section.

![screen shot 2015-03-08 at 9 45 48 pm](https://cloud.githubusercontent.com/assets/11359229/6548848/c6461bae-c5dc-11e4-8f7e-60be9c6fb2b8.png)

**Comment by pdpinch** [comment]
I feel like I got a comment from Alison somewhere saying that it would be OK to pop this into a new window, thus avoiding the problem altogether.

**Comment by laleman** [comment]
It was me. Yes, we can do this into a new window. :)

**Comment by annagav** [comment]
Fixed by #103.
