### ISSUE TITLE
SUTD Exercise #2 - Microscopy: Images appear superimposed on top of the round view finder

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#76]
This is the same issues previously encountered in other exercises.
![screen shot 2015-03-08 at 9 51 08 pm](https://cloud.githubusercontent.com/assets/11359229/6548870/45131338-c5dd-11e4-974a-1c455a8511a1.png)

**Comment by pdpinch** [comment]
same issue as #56

**Comment by pdpinch** [comment]
@ald32 @laleman please review on scbdev.mit.edu

**Comment by ald32** [comment]
The images now appear properly contained within the microscope lens for me. I do notice that the In the Lab video reloads every time I select a new sample. Is there any way to prevent this from happening?

**Comment by ald32** [comment]
I just realized that I was looking at SUTD Exercise #1 (where the images do appear correctly). In SUTD exercise #2, the images are appearing much smaller than the lens and should be enlarged (see attached image).
![screen shot 2015-03-10 at 1 43 05 pm](https://cloud.githubusercontent.com/assets/1855065/6581141/66860760-c72b-11e4-9324-9a12adf0c83f.png)

**Comment by pdpinch** [comment]
Closing this issue and opening two new ones for the other feedback: #92 and #93
