### ISSUE TITLE
SUTD Exercise #2 - Microscopy: Images are all different sizes for the different samples provided

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#77]
The images are displayed at different resolutions for different samples. 
![screen shot 2015-03-08 at 9 51 08 pm](https://cloud.githubusercontent.com/assets/11359229/6548888/9b3635e2-c5dd-11e4-8e57-44e23453fcf5.png)
![screen shot 2015-03-08 at 9 53 05 pm](https://cloud.githubusercontent.com/assets/11359229/6548889/9d195132-c5dd-11e4-8bbc-63ec24498fdd.png)
![screen shot 2015-03-08 at 9 53 32 pm](https://cloud.githubusercontent.com/assets/11359229/6548890/9ec3c12a-c5dd-11e4-8e0d-ced0e9036a7f.png)

**Comment by pdpinch** [comment]
@laleman each of these images is exactly the size provided (you can check URLs below). Should we be increasing their resolution? If so, how much?

Similarly, should large images be adjusted as well?

https://scbdev.mit.edu/images/microscopy/sutd_2/rna1/Metaphase_arrest2.jpg
https://scbdev.mit.edu/images/microscopy/sutd_2/rna2/MT_instability2.jpg
https://scbdev.mit.edu/images/microscopy/sutd_2/rna3/Interphase_10Normal_UnequalChromsomeDistribution4_composite.jpg
https://scbdev.mit.edu/images/microscopy/sutd_2/cn/Interphase_10Normal_Metaphase_4Normal_Anaphase_1_composite.jpg

**Comment by laleman** [comment]
Hi Peter. Control siRNA related images are composite images that Shloka generated last year. I did not noticed that they were substantially bigger. The rest of the images I cropped myself from original sources according to the dimensions that we used last year to generate single images (not composites). All images should be 148x148 (I noticed that siRNA  #2 image called "MIT instability 1" is actually a little smaller 146x146 --> I can correct this to be 148x148). Shloka must have adjusted the images last year because they basically all look like the same size. Can you and Anna take a look at 2014 7.06 Assignment #2 to see how this was dealt with?

**Comment by pdpinch** [comment]
Will do. 

Can you remind us what the course code is for 7.06?

> Can you and Anna take a look at 2014 7.06 Assignment #2 to see how this was dealt with?

**Comment by laleman** [comment]
It is: 7.06_Spring_2014

**Comment by pdpinch** [comment]
It looks like the images in that exercise were all 400x400

https://starcellbio.mit.edu/images/microscopy/assignment_706_2014_ps2/Antibody_Labeling_DNA-blue_Mad2-red/Mad2_on_kinetochore/Mad2_kinetochore_cropped.jpg

https://starcellbio.mit.edu/images/microscopy/assignment_706_2014_ps2/Antibody_Labeling_DNA-blue_Mad2-red/Mad2_on_kinetochore/Mad2_kinetochore_cropped.jpg

If you have higher-resolution originals (higher than 148x148) we should probably use those. If you don't then we can up-res the ones we have. 

I'm still not sure what we're supposed to do with composite images, like https://scbdev.mit.edu/images/microscopy/sutd_2/cn/Interphase_10Normal_Metaphase_4Normal_Anaphase_1_composite.jpg The current behavior doesn't seem right to me.

**Comment by laleman** [comment]
Hi Peter. The images in this reply were slightly bigger but there were other images that were also 146x146 or 148x148 in last year's 7.06 assignment. I can see if I can get higher resolution images but this will involve substantial amount of work to dig and find some of the original files with thousands of images from last spring. All the images files used within last year's 7.06 Assignment are in the Dropbox folder: StarCellBio --> 7.06 --> 2014 Spring --> StarCellBio Quizzes --> Problem 2 - Cell Cycle --> Microscopy Images --> StarCellBio Microscopy Images. The composite images were also used. Thoughts?

**Comment by laleman** [comment]
Working properly now. All images are at the same resolution. Thank you.
