### ISSUE TITLE
New installation errors 

### ISSUE THREAD

**Issue by jmclaus** [starteam/starcellbio_html#770]
@annagav @idegtiarov @auraz

Errors now appear on a brand new installation on provisioning:

`Make sure the development packages of libxml2 and libxslt are installed.`

this can be solved by installing these ([check here](https://stackoverflow.com/questions/6504810/how-to-install-lxml-on-ubuntu#6504860))

`sudo apt-get install libxml2-dev libxslt1-dev python-dev`

Then on entry page load, we get a series of errors:

No module named lxml ... urllib3 ... chardet ... certifi ... idna

that can be solved by running:

`pip install lxml urllib3 chardet certifi idna`

We should update `provision/ansible-dev.yml` to get rid of these.

**Comment by pdpinch** [comment]
@blarghmatey did you already fix this?

**Comment by blarghmatey** [comment]
Not yet. I hadn't noticed this ticket before but I can get it added fairly quickly. I'll put it on my list for Monday.
