### ISSUE TITLE
SUTD Exercise #2 - Hand cursor for hovering over state is missing

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#78]
There used to be a hand cursor when hovering over all buttons and the navigation bar. Now I only see the arrow cursor. This bug is present for Alison but not for Lourdes.

**Comment by pdpinch** [comment]
Are you using the same versions of Chrome?

It's possible this could be the result of a transient state in your browser. When you have a chance, it would be good to quit and restart and see if the issue persists.

**Comment by laleman** [comment]
OK, I will ask Alison to do this since she was the one experiencing this issue.

**Comment by ald32** [comment]
I just looked at it again and the hand cursor is appearing. I am using Google Chrome version 41.0.2272.76 - it says that it's up to date.

**Comment by pdpinch** [comment]
I'll close this for now. Feel free to re-open, or add a new issue if you see this problem again.
