### ISSUE TITLE
Handle error when instructor tries to publish assignment without 'Assignment Text' or 'Upload Assignment Files'

### ISSUE THREAD

**Issue by annagav** [starteam/starcellbio_html#780]

**Comment by jmclaus** [comment]
@annagav Thanks for the feedback. This has been addressed in a PR I just opened:

https://github.com/starteam/starcellbio_html/pull/779

**Comment by jmclaus** [comment]
@annagav Closing this as https://github.com/starteam/starcellbio_html/pull/779 has been merged.
