### ISSUE TITLE
SUTD Exercise #2 - Microscopy: Pop-up window text get cut off at the bottom.

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#87]
This issue is currently present within the production site as well. 

https://scbdev.mit.edu/#view=microscopy&experiment_id=scb_Experiment_bp068o1bmqk3f&assignment_id=sutd_intro_biology_ps2&microscopy_id=scb_Microscopy_1ef164i15q3c13
![screen shot 2015-03-10 at 3 29 58 pm](https://cloud.githubusercontent.com/assets/11359229/6583460/b13a9b04-c73a-11e4-91d9-2d2257695631.png)

**Comment by annagav** [comment]
last paragraph was removed.
