### ISSUE TITLE
StarCellBio Production Site: Assignments Page

### ISSUE THREAD

**Issue by laleman** [starteam/starcellbio_html#88]
Before Ivan left, he made 7.06 Spring 2014 StarCellBio Assignment 1 visible without creating an account (can be accessed by clicking on the "Try An Experiment" on the Home Page) so that SUTD instructors, who were trying out StarCellBio for the first time, could access it without a course code, etc. This assignment is the basis for the SUTD Exercise #1. However, before we push the SUTD assignments live, we should make sure that 7.06 Spring 2014 StarCellBio Assignment 1 is no longer present in the assignments that are visible to folks without an account. It should still remain in the 7.06 Spring 2014 course list, which can be accessed with the corresponding course code: 7.06_Spring_2014. 

https://starcellbio.mit.edu/#view=assignments&assignment_id=assignment_706_2014

![screen shot 2015-03-10 at 3 40 09 pm](https://cloud.githubusercontent.com/assets/11359229/6583749/87a14408-c73c-11e4-853f-02d7d8aedd56.png)

**Comment by pdpinch** [comment]
Thanks for the reminder Lourdes.

So, the way things are set up now, the production server will be the same as the Dev server when it's deployed. 

Can you check dev to see if it works as you intend (esp., does the 7.06 course code work)? If it does, we're all set. If not, we have some work to do.

FYI @bdero

---

I am mobile.

**Comment by laleman** [comment]
Hi Peter. I just logged on onto the StarDev site using 7.06's Course Code, etc and I was able to access the 7.06 assignments without any issues. All of my previous data from performing experiments within these exercises are gone. Would we expect that too?

**Comment by pdpinch** [comment]
Good to hear that you can still access 7.06.

Yes, your data will still be there, unless we remove the student accounts as we've doing on scbdev.

**Comment by pdpinch** [comment]
I will close this once we have a production site.

**Comment by pdpinch** [comment]
Oops. Should have closed this back on Friday the 13th.
