### ISSUE TITLE
In SUTD exercise #2, images are much smaller than the lens

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#93]
From #76:

> In SUTD exercise #2, the images are appearing much smaller than the lens and should be enlarged (see attached image).

**Comment by pdpinch** [comment]
This should have been fixed yesterday by f6d855e

@ald32 can you check to see if this is still happening & let us know? Thanks.

**Comment by laleman** [comment]
Hi Peter. This comment was made prior to the fix.

**Comment by ald32** [comment]
The images appear correctly for me now. :)
