### ISSUE TITLE
Remove empty column for conditions (SUTD #2, Flow Cytometry)

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#94]
SUTD Exercise #2 - Flow Cytometry has an empty column for conditions. It would be best if it were removed when empty. 

Remaining work from #72

**Comment by annagav** [comment]
@ald32 Is this still relevant? In the assignment builder do we want to have an option to not display the conditions column?

**Comment by ald32** [comment]
This is still relevant. In the case when there aren't any conditions specified, then it would be best if the conditions column doesn't display at all. Is that possible? I think that option would be better than having the instructors have to choose the option to not display the conditions column.

**Comment by annagav** [comment]
@ald32 Right now in the assignment builder the instructor is required to enter a condition. Do we want to allow a blank condition?

**Comment by ald32** [comment]
@annagav I think it's ok to just have the fixed/live and the analysis as long as it doesn't cause problems in the back end.

**Comment by annagav** [comment]
This is not relevant. In the AB we the propidium iodide is now the condition and the analysis is Dye/Stain.
<img width="650" alt="screen shot 2016-10-21 at 4 49 48 pm" src="https://cloud.githubusercontent.com/assets/7574259/19611060/de4c3ed2-97ad-11e6-86a4-b3aae4fa7a2c.png">
